import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter/material.dart';

const termsAndConditionsUrl = 'https://snaplet.art/terms-of-service/';
const privacypolicyurl = 'https://snaplet.art/privacy-policy/';

const apiKey =
    'key-52ufVjvvgYbfEP7Q21otUGbs2J9tSc7r1SZA7MVVxv4fuTlPvWhKgfD7mX2YkfHKRbR0DwSUhuWaDDfwDXmniq6ZKioAlFfP';

const String googleCloudApiKey = 'AIzaSyCXUsfyGomwM2jJf9REb6IvZNsyDuV5Za8';


//************************************************************************* */
const stableDiffusionTextToImage =
    'https://api.getimg.ai/v1/stable-diffusion/text-to-image';
const latentConsTextToImage =
    'https://api.getimg.ai/v1/latent-consistency/text-to-image';
const stableXItextToimage =
    'https://api.getimg.ai/v1/stable-diffusion-xl/text-to-image';
//************************************************************************* */
const allModels = 'https://api.getimg.ai/v1/models';
//************************************************************************* */
const stableDiffusionImageToImage =
    'https://api.getimg.ai/v1/stable-diffusion/image-to-image';
const latentConsImageToImage =
    'https://api.getimg.ai/v1/latent-consistency/image-to-image';
const stableXIimageToimage =
    'https://api.getimg.ai/v1/stable-diffusion-xl/image-to-image';
const essintialUrl = 'https://api.getimg.ai/v1/essential/text-to-image';
//************************************************************************* */
const enhansUpScale = 'https://api.getimg.ai/v1/enhancements/upscale';
const enhansFixFaces = 'https://api.getimg.ai/v1/enhancements/face-fix';
const inpaintUrl = 'https://api.getimg.ai/v1/stable-diffusion/inpaint';
const instructUrl = 'https://api.getimg.ai/v1/stable-diffusion/instruct';

List<String> images = [
  'assets/getimgimages/1.jpeg',
  'assets/getimgimages/2.png',
  'assets/getimgimages/3.jpg',
  'assets/getimgimages/4.jpg',
  'assets/getimgimages/5.jpeg',
  'assets/getimgimages/6.jpeg',
  'assets/getimgimages/7.jpeg',
  'assets/getimgimages/8.jpg',
  'assets/getimgimages/9.jpeg',
  'assets/getimgimages/10.png',
  'assets/getimgimages/11.png',
  'assets/getimgimages/12.png',
  'assets/getimgimages/13.jpeg',
  'assets/getimgimages/14.png',
  'assets/getimgimages/16.jpg',
  'assets/getimgimages/17.jpg',
  'assets/getimgimages/18.jpg',
  'assets/getimgimages/19.jpeg',
  'assets/getimgimages/20.jpeg',
  'assets/getimgimages/21.jpeg',
  'assets/getimgimages/22.jpeg',
  'assets/getimgimages/23.jpg',
  'assets/getimgimages/24.png',
  'assets/getimgimages/25.png',
  'assets/getimgimages/26.jpeg',
  'assets/getimgimages/27.png',
  'assets/getimgimages/28.jpeg',
  'assets/getimgimages/29.jpg',
  'assets/getimgimages/30.jpeg',
  'assets/getimgimages/31.jpg',
  'assets/getimgimages/33.png',
  'assets/getimgimages/34.jpeg',
  'assets/getimgimages/35.jpeg',
  'assets/getimgimages/36.jpeg',
  'assets/getimgimages/37.jpg',
  'assets/getimgimages/38.png',
  'assets/getimgimages/39.png',
  'assets/getimgimages/40.png',
  'assets/getimgimages/45.jpg',
  'assets/getimgimages/46.png',
];

List<String> inpaint = [
  'assets/getimgimages/15.jpeg',
  'assets/getimgimages/16.jpg',
  'assets/getimgimages/32.png',
  'assets/getimgimages/41.png',
];

// List<String> enhancementsimgs = [];

// List<String> instruct = [];

void showNoInternetDialog(BuildContext context) {
  showDialog(
    context: context,
    builder: (context) => AlertDialog(
      title: const Text('No Internet Connection'),
      content: const Text('Please check your internet connection and try again.'),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('OK'),
        ),
      ],
    ),
  );
}
Future<bool> checkInternetConnection() async {
  var connectivityResult = await Connectivity().checkConnectivity();
  if (connectivityResult.contains(ConnectivityResult.mobile)) {
    return true; 
  }else if(connectivityResult.contains(ConnectivityResult.wifi)){
    return true;
  }
  return false;
}


Set<String> bannedWords = {
  's3x',
  's3xy',
  's*x',
  '\$ex',
  'a\$\$',
  '@ss',
  '@n@l',
  'p*rn',
  'pr0n',
  'p0rn',
  'b00bs',
  'c0ck',
  'c*ck',
  'd1ck',
  'd!ck',
  'f*ck',
  'f@ck',
  'f*ggot',
  'f@ggot',
  'p*ssy',
  'p@ssy',
  'faggot',
  'girl hot',
  
  'gay',
  'gilf',
  'lesbian',
  'bisexual',
  'sexting',
  'strip',
  "*",
  "#",
  "2g1c",
  "blowjob",
  "g spot",
  "booty",
  "desnuda",
  "desnudo",
  "nudo",
  "nuda",
  "acrotomophilia",
  "alabama hot pocket",
  "alaskan pipeline",
  "anal",
  "anilingus",
  "anus",
  "apeshit",
  "arsehole",
  // "ass",
  "asshole",
  "assmunch",
  "auto erotic",
  "autoerotic",
  "babeland",
  "baby batter",
  "baby juice",
  "ball gag",
  "ball gravy",
  "ball kicking",
  "ball licking",
  "ball sack",
  "ball sucking",
  "bangbros",
  "bangbus",
  "bareback",
  "barely legal",
  "naked",
  "barenaked",
  "bastard",
  "bastardo",
  "bastinado",
  "bbw",
  "bdsm",
  "beaner",
  "beaners",
  "beaver cleaver",
  "beaver lips",
  "beastiality",
  "bestiality",
  "big breasts",
  "big knockers",
  "big tits",
  "bimbos",
  "birdlock",
  "bitch",
  "bitches",
  "black cock",
  "blonde action",
  "blonde on blonde action",
  "blow job",
  "blow your load",
  "blue waffle",
  "blumpkin",
  "bollocks",
  "bondage",
  "boner",
  "boob",
  "boobs",
  "booty call",
  "brown showers",
  "brunette action",
  "bukkake",
  "bulldyke",
  "bullet vibe",
  "bullshit",
  "bung hole",
  "bunghole",
  "busty",
  "butt",
  "buttcheeks",
  "butthole",
  "camel toe",
  "camgirl",
  "camslut",
  "camwhore",
  "carpet muncher",
  "carpetmuncher",
  "chocolate rosebuds",
  "cialis",
  "circlejerk",
  "cleveland steamer",
  "clit",
  "clitoris",
  "clover clamps",
  "clusterfuck",
  "cock",
  "cocks",
  "coprolagnia",
  "coprophilia",
  "cornhole",
  "coon",
  "coons",
  "creampie",
  "cum",
  "cumming",
  "cumshot",
  "cumshots",
  "cunnilingus",
  "cunt",
  "darkie",
  "date rape",
  "daterape",
  "deep throat",
  "deepthroat",
  "dendrophilia",
  "dick",
  "dildo",
  "dingleberry",
  "dingleberries",
  "dirty pillows",
  "dirty sanchez",
  "doggie style",
  "doggiestyle",
  "doggy style",
  "doggystyle",
  "dog style",
  "dolcett",
  "domination",
  "dominatrix",
  "dommes",
  "donkey punch",
  "double dong",
  "double penetration",
  "dp action",
  "dry hump",
  "dvda",
  "eat my ass",
  "ecchi",
  "ejaculation",
  "erotic",
  "erotism",
  "escort",
  "eunuch",
  "fag",
  "fecal",
  'NSFW ',
  'BBC',
  'DTF',
  'HJ',
  'bj',
  'LGBTQ+',
  "felch",
  "fellatio",
  "feltch",
  "female squirting",
  "femdom",
  "figging",
  "fingerbang",
  "fingering",
  "fisting",
  "foot fetish",
  "footjob",
  "frotting",
  "fuck",
  "fuck buttons",
  "fuckin",
  "fucking",
  "fucktards",
  "fudge packer",
  "fudgepacker",
  "futanari",
  "gangbang",
  "gang bang",
  "gay sex",
  "genitals",
  "giant cock",
  "girl on",
  "girl on top",
  "girls gone wild",
  "goatcx",
  "goatse",
  "god damn",
  "gokkun",
  "golden shower",
  "goodpoop",
  "goo girl",
  "goregasm",
  "grope",
  "group sex",
  "g-spot",
  "guro",
  "hand job",
  "handjob",
  "hard core",
  "hardcore",
  "hentai",
  "homoerotic",
  "honkey",
  "hooker",
  "horny",
  "hot carl",
  "hot chick",
  "how to kill",
  "how to murder",
  "huge fat",
  "humping",
  "incest",
  "intercourse",
  "jack off",
  "jail bait",
  "jailbait",
  "jelly donut",
  "jerk off",
  "jigaboo",
  "jiggaboo",
  "jiggerboo",
  "jizz",
  "juggs",
  "kike",
  "kinbaku",
  "kinkster",
  "kinky",
  "knobbing",
  "leather restraint",
  "leather straight jacket",
  "lemon party",
  "livesex",
  "lolita",
  "lovemaking",
  "make me come",
  "male squirting",
  "masturbate",
  "masturbating",
  "masturbation",
  "menage a trois",
  "milf",
  "missionary position",
  "mong",
  "motherfucker",
  "mound of venus",
  "mr hands",
  "muff diver",
  "muffdiving",
  "nambla",
  "nawashi",
  "negro",
  "neonazi",
  "nigga",
  "nigger",
  "nig nog",
  "nimphomania",
  "nipple",
  "nipples",
  "nsfw",
  "nsfw images",
  "nude",
  "nudity",
  "nutten",
  "nympho",
  "nymphomania",
  "octopussy",
  "omorashi",
  "one guy one jar",
  "orgasm",
  "orgy",
  "paedophile",
  "paki",
  "panties",
  "panty",
  "pedobear",
  "pedophile",
  "pegging",
  "penis",
  "phone sex",
  'hot guy',
  'hot guys',
  'hot girl',
  'hot man',
  'hot woman',
  'hot women',
  'hot men',
  "piece of shit",
  "pikey",
  "pissing",
  "piss pig",
  "pisspig",
  "playboy",
  "pleasure chest",
  "pole smoker",
  "ponyplay",
  "poof",
  "poon",
  "poontang",
  "punany",
  "poop chute",
  "poopchute",
  "porn",
  "porno",
  "pornography",
  "prince albert piercing",
  "pthc",
  "pubes",
  "pussy",
  "queaf",
  "queef",
  "quim",
  "raghead",
  "raging boner",
  "rape",
  "raping",
  "rapist",
  "rectum",
  'f*cked up',
  'jerk',
  'jirk',
  "reverse cowgirl",
  "rimjob",
  "rimming",
  "rosy palm",
  "rosy palm and her 5 sisters",
  "rusty trombone",
  "sadism",
  "santorum",
  "scat",
  "schlong",
  "scissoring",
  "semen",
  "sex",
  "sexcam",
  "sexo",
  "sexy",
  "sexual",
  "sexually",
  "sexuality",
  'deck',
  "shaved beaver",
  "shaved pussy",
  "shemale",
  "shibari",
  "shit",
  "shitblimp",
  "shitty",
  "shota",
  "shrimping",
  "skeet",
  'stripping',
  "slanteye",
  "slut",
  "s&m",
  "smut",
  'nakey',
  'nake',
  'playing in ass',
  'vagina',
  "snatch",
  "snowballing",
  "sodomize",
  "sodomy",
  "spastic",
  "spic",
  "splooge",
  "splooge moose",
  "spooge",
  "spread legs",
  "spunk",
  "strap on",
  "strapon",
  "strappado",
  "strip club",
  "style doggy",
  "suck",
  "sucks",
  "suicide girls",
  "sultry women",
  "swastika",
  "swinger",
  "tainted love",
  "threesome",
  "throating",
  "thumbzilla",
  "tied up",
  "tight white",
  "tit",
  "tits",
  "titties",
  "titty",
  "tongue in a",
  "topless",
  "tosser",
  "towelhead",
  "tranny",
  "tribadism",
  "tub girl",
  "tubgirl",
  "tushy",
  "twat",
  "twink",
  "twinkie",
  "undressing",
  "upskirt",
  "urethra play",
  "urophilia",
  "venus mound",
  'sex toy',
  "viagra",
  "vibrator",
  "violet wand",
  "vorarephilia",
  "voyeur",
  "voyeurweb",
  "voyuer",
  "vulva",
  "wank",
  "wetback",
  "wet dream",
  "white power",
  "whore",
  "worldsex",
  "wrapping men",
  "wrinkled starfish",
  "xx",
  "xxx",
  "yaoi",
  "yellow showers",
  "yiffy",
  "zoophilia",
  "bychara",
  "byk",
  "chernozhopyi",
  "dolboy'eb",
  "ebalnik",
  "ebalo",
  "ebalom sch'elkat",
  "gol",
  "mudack",
  "opizdenet",
  "osto'eblo",
  "ostokhuitel'no",
  "otmudohat",
  "otpizdit",
  "otsosi",
  "padlo",
  "pedik",
  "perdet",
  "petuh",
  "pidar gnoinyj",
  "pizda",
  "pizdato",
  "pizdatyi",
  "piz'det",
  "pizdetc",
  "pizdoi nakryt'sja",
  "podi ku'evo",
  "poeben",
  "po khuy",
  "poluchit pizdy",
  "pososi moyu konfetku",
  "prissat",
  "proebat",
  "promudobl'adsksya pizdopro'ebina",
  "propezdoloch",
  "prosrat",
  "raspeezdeyi",
  "raspizdatyi",
  "shalava",
  "styervo",
  "sukin syn",
  "svodit posrat",
  "svoloch",
  "trimandoblydskiy pizdoproyob",
  "uboy",
  "vafli lovit",
  "v pizdu",
  "vyperdysh",
  "vzdrochennyi",
  "yeb vas",
  "za'ebat",
  "zaebis",
  "zalupa",
  "zalupat",
  "zasranetc",
  "zassat",
  "am",
  "amlar",
  "kaltak",
  "kaltaklar",
  "kaltaklara",
  "kaltaklarda",
  "kaltaklardan",
  "kaltakta",
  "kaltaktan",
  "orospu",
  "orospuda",
  "orospudan",
  "orospular",
  "orospulara",
  "orospularda",
  "orospulardan",
  "orospunun",
  "orospuya",
  "orospuyu",
  "otuz birci",
  "otuz bircide",
  "otuz birciden",
  "otuz birciler",
  "otuz bircilerde",
  "otuz bircilerden",
  "otuz bircilere",
  "otuz bircileri",
  "otuz bircilerin",
  "otuz bircinin",
  "otuz birciye",
  "otuz birciyi",
  "saksocu",
  "saksocuda",
  "saksocudan",
  "saksocular",
  "saksoculara",
  "saksocularda",
  "saksoculardan",
  "saksocunun",
  "saksocuya",
  "saksocuyu",
  "sik",
  "sike",
  "siker sikmez",
  "siki",
  "sikilir sikilmez",
  "sikin",
  "sikler",
  "siklerde",
  "siklerden",
  "siklere",
  "sikleri",
  "siklerin",
  "sikmek",
  "sikmemek",
  "sikte",
  "sikten",
  "siktir",
  "siktirir siktirmez",
  "yarak",
  "yaraklar",
  "yaraklara",
  "yaraklarda",
  "yaraklardan",
  "yarakta",
  "yaraktan",
  "arsle",
  "brutta",
  "discofitta",
  "fitta",
  "fittig",
  "för helvete",
  "helvete",
  "hård",
  "jävlar",
  "knulla",
  "kuk",
  "kuksås",
  "kötthuvud",
  "köttnacke",
  "moona",
  "moonade",
  "moonar",
  "moonat",
  "mutta",
  "neger",
  "olla",
  "pippa",
  "pitt",
  "prutt",
  "runka",
  "satan",
  "skita",
  "skit ner dig",
  "snedfitta",
  "snefitta",
  "stake",
  "subba",
  "sås",
  "sätta på",
  "tusan",
  "Asesinato",
  "asno",
  "Bollera",
  "Cabrón",
  "Caca",
  "Chupada",
  "Chupapollas",
  "Chupetón",
  "concha",
  "Concha de tu madre",
  "Coño",
  "Coprofagía",
  "Culo",
  "Drogas",
  "Esperma",
  "Fiesta de salchichas",
  "Follador",
  "Follar",
  "Gilipichis",
  "Gilipollas",
  "Hacer una paja",
  "Haciendo el amor",
  "Heroína",
  "Hija de puta",
  "Hijaputa",
  "Hijo de puta",
  "Hijoputa",
  "Idiota",
  "Imbécil",
  "infierno",
  "Jilipollas",
  "Kapullo",
  "Lameculos",
  "Maciza",
  "Macizorra",
  "maldito",
  "Mamada",
  "Marica",
  "Maricón",
  "Mariconazo",
  "martillo",
  "Mierda",
  "Nazi",
  "Orina",
  "Pedo",
  "Pendejo",
  "Pervertido",
  "Pezón",
  "Pinche",
  "Pis",
  "Prostituta",
  "Puta",
  "Racista",
  "Ramera",
  "Sádico",
  "Semen",
  "Sexo",
  "Sexo oral",
  "Soplagaitas",
  "Soplapollas",
  "Tetas grandes",
  "Tía buena",
  "Travesti",
  "Trio",
  "Verga",
  "vete a la mierda",
  "Vulva",
  "aborto",
  "amador",
  "ânus",
  "aranha",
  "ariano",
  "balalao",
  "bicha",
  "biscate",
  "bissexual",
  "boceta",
  "bosta",
  "braulio de borracha",
  "bumbum",
  "burro",
  "cabrao",
  "cacete",
  "cagar",
  "camisinha",
  "caralho",
  "cerveja",
  "chochota",
  "chupar",
  "cocaína",
  "coito",
  "colhoes",
  "comer",
  "cona",
  "consolo",
  "corno",
  "dar o rabo",
  "dum raio",
  "esporra",
  "filho da puta",
  "foda",
  "foda-se",
  "foder",
  "frango assado",
  "gozar",
  "grelho",
  "heroína",
  "heterosexual",
  "homem gay",
  "homoerótico",
  "homosexual",
  "inferno",
  "lésbica",
  "mama",
  "merda",
  "paneleiro",
  "passar um cheque",
  "pau",
  "peidar",
  "pênis",
  "pinto",
  "porra",
  "puta",
  "puta que pariu",
  "puta que te pariu",
  "queca",
  "sacanagem",
  "saco",
  "torneira",
  "transar",
  "vadia",
  "vai-te foder",
  "vai tomar no cu",
  "veado",
  "vibrador",
  "xana",
  "xochota",
  "burdel",
  "burdelmama",
  "chuj",
  "chujnia",
  "ciota",
  "cipa",
  "cyc",
  "debil",
  "dmuchać",
  "do kurwy nędzy",
  "dupa",
  "dupek",
  "duperele",
  "dziwka",
  "fiut",
  "gówno",
  "gówno prawda",
  "huj",
  "huj ci w dupę",
  "jajco",
  "jajko",
  "ja pierdolę",
  "jebać",
  "jebany",
  "kurwa",
  "kurwy",
  "kutafon",
  "kutas",
  "pierdolec",
  "pierdoła",
  "pojeb",
  "pojebany",
  "popierdolony",
  "robic loda",
  "robić loda",
  "ruchać",
  "rzygać",
  "skurwysyn",
  "sraczka",
  "srać",
  "suka",
  "syf",
  "zajebisty",
  "dritt",
  "drittsekk",
  "faen",
  "faen i helvete",
  "fanken",
  "fitte",
  "forbanna",
  "forbannet",
  "fy faen",
  "helvetet",
  "kukene",
  "kuker",
  "morraknuller",
  "morrapuler",
  "pakkis",
  "pikk",
  "pokker",
  "sinnsykt",
  "skitt",
  "svartheiteste",
  "abbuc",
  "qqu",
  "qqan",
  "qqant",
  "tteqqun",
  "tteqqunt",
  "aqerqur",
  "ajeḥniḍ",
  "awellaq",
  "iwellaqen",
  "iḥeččan",
  "iḥeččunen",
  "uqan",
  "taxna",
  "allupato",
  "ammucchiata",
  "anale",
  "arrapato",
  "arrusa",
  "arruso",
  "assatanato",
  "bagascia",
  "bagassa",
  "bagnarsi",
  "baldracca",
  "balle",
  "battere",
  "battona",
  "belino",
  "biga",
  "bocchinara",
  "bocchino",
  "bofilo",
  "boiata",
  "bordello",
  "brinca",
  "bucaiolo",
  "budiùlo",
  "busone",
  "cacca",
  "caciocappella",
  "cadavere",
  "cagare",
  "cagata",
  "cagna",
  "casci",
  "cazzata",
  "cazzimma",
  "cazzo",
  "cesso",
  "cazzone",
  "checca",
  "chiappa",
  "chiavare",
  "chiavata",
  "ciospo",
  "ciucciami il cazzo",
  "coglione",
  "coglioni",
  "cornuto",
  "cozza",
  "culattina",
  "culattone",
  "culo",
  "ditalino",
  "fava",
  "femminuccia",
  "fica",
  "figa",
  "figlio di buona donna",
  "figlio di puttana",
  "figone",
  "finocchio",
  "fottere",
  "fottersi",
  "fracicone",
  "fregna",
  "frocio",
  "froscio",
  "goldone",
  "guardone",
  "imbecille",
  "incazzarsi",
  "incoglionirsi",
  "ingoio",
  "leccaculo",
  "lecchino",
  "lofare",
  "loffa",
  "loffare",
  "mannaggia",
  "merdata",
  "merdoso",
  "mignotta",
  "minchia",
  "minchione",
  "mona",
  "monta",
  "montare",
  "mussa",
  "nave scuola",
  "nerchia",
  "padulo",
  "palle",
  "palloso",
  "patacca",
  "patonza",
  "pecorina",
  "pesce",
  "picio",
  "pincare",
  "pinnolone",
  "pipì",
  "pippone",
  "pirla",
  "pisciare",
  "piscio",
  "pisello",
  "pistolotto",
  "pomiciare",
  "pompa",
  "pompino",
  "porca",
  "porca madonna",
  "porca miseria",
  "porca puttana",
  "porco",
  "porco due",
  "porco zio",
  "potta",
  "puppami",
  "puttana",
  "quaglia",
  "recchione",
  "regina",
  "rincoglionire",
  "rizzarsi",
  "rompiballe",
  "rompipalle",
  "ruffiano",
  "sbattere",
  "sbattersi",
  "sborra",
  "sborrata",
  "sborrone",
  "sbrodolata",
  "scopare",
  "scopata",
  "scorreggiare",
  "sega",
  "slinguare",
  "slinguata",
  "smandrappata",
  "soccia",
  "socmel",
  "sorca",
  "spagnola",
  "spompinare",
  "sticchio",
  "stronza",
  "stronzata",
  "stronzo",
  "succhiami",
  "succhione",
  "sveltina",
  "sverginare",
  "tarzanello",
  "terrone",
  "testa di cazzo",
  "tette",
  "tirare",
  "topa",
  "troia",
  "trombare",
  "vacca",
  "vaffanculo",
  "vangare",
  "zinne",
  "zio cantante",
  "zoccola",
  "balfasz",
  "balfaszok",
  "balfaszokat",
  "balfaszt",
  "barmok",
  "barmokat",
  "barmot",
  "barom",
  "baszik",
  "bazmeg",
  "buksza",
  "bukszák",
  "bukszákat",
  "bukszát",
  "búr",
  "búrok",
  "csöcs",
  "csöcsök",
  "csöcsöket",
  "csöcsöt",
  "fasz",
  "faszfej",
  "faszfejek",
  "faszfejeket",
  "faszfejet",
  "faszok",
  "faszokat",
  "faszt",
  "fing",
  "fingok",
  "fingokat",
  "fingot",
  "franc",
  "francok",
  "francokat",
  "francot",
  "geci",
  "gecibb",
  "gecik",
  "geciket",
  "gecit",
  "kibaszott",
  "kibaszottabb",
  "kúr",
  "kurafi",
  "kurafik",
  "kurafikat",
  "kurafit",
  "kurva",
  "kurvák",
  "kurvákat",
  "kurvát",
  "leggecibb",
  "legkibaszottabb",
  "legszarabb",
  "marha",
  "marhák",
  "marhákat",
  "marhát",
  "megdöglik",
  "pele",
  "pelék",
  "picsa",
  "picsákat",
  "picsát",
  "pina",
  "pinák",
  "pinákat",
  "pinát",
  "pofa",
  "pofákat",
  "pofát",
  "pöcs",
  "pöcsök",
  "pöcsöket",
  "pöcsöt",
  "punci",
  "puncik",
  "segg",
  "seggek",
  "seggeket",
  "segget",
  "seggfej",
  "seggfejek",
  "seggfejeket",
  "seggfejet",
  "szajha",
  "szajhák",
  "szajhákat",
  "szajhát",
  "szar",
  "szarabb",
  "szarik",
  "szarok",
  "szarokat",
  "szart",
  "aand",
  "aandu",
  "balatkar",
  "balatkari",
  "behen chod",
  "beti chod",
  "bhadva",
  "bhadve",
  "bhandve",
  "bhangi",
  "bhootni ke",
  "bhosad",
  "bhosadi ke",
  "boobe",
  "chakke",
  "chinaal",
  "chinki",
  "chod",
  "chodu",
  "chodu bhagat",
  "chooche",
  "choochi",
  "choope",
  "choot",
  "choot ke baal",
  "chootia",
  "chootiya",
  "chuche",
  "chuchi",
  "chudaap",
  "chudai khanaa",
  "chudam chudai",
  "chude",
  "chut",
  "chut ka chuha",
  "chut ka churan",
  "chut ka mail",
  "chut ke baal",
  "chut ke dhakkan",
  "chut maarli",
  "chutad",
  "chutadd",
  "chutan",
  "chutia",
  "chutiya",
  "gaand",
  "gaandfat",
  "gaandmasti",
  "gaandufad",
  "gandfattu",
  "gandu",
  "gashti",
  "gasti",
  "ghassa",
  "ghasti",
  "gucchi",
  "gucchu",
  "harami",
  "haramzade",
  "hawas",
  "hawas ke pujari",
  "hijda",
  "hijra",
  "jhant",
  "jhant chaatu",
  "jhant ka keeda",
  "jhant ke baal",
  "jhant ke pissu",
  "jhantu",
  "kamine",
  "kaminey",
  "kanjar",
  "kutta",
  "kutta kamina",
  "kutte ki aulad",
  "kutte ki jat",
  "kuttiya",
  "loda",
  "lodu",
  "lund",
  "lund choos",
  "lund ka bakkal",
  "lund khajoor",
  "lundtopi",
  "lundure",
  "maa ki chut",
  "maal",
  "madar chod",
  "madarchod",
  "madhavchod",
  "mooh mein le",
  "mutth",
  "mutthal",
  "najayaz",
  "najayaz aulaad",
  "najayaz paidaish",
  "pataka",
  "patakha",
  "raand",
  "randaap",
  "randi",
  "randi rona",
  "saala",
  "saala kutta",
  "saali kutti",
  "saali randi",
  "suar",
  "suar ke lund",
  "suar ki aulad",
  "tatte",
  "tatti",
  "teri maa ka bhosada",
  "teri maa ka boba chusu",
  "teri maa ki behenchod ",
  "teri maa ki chut",
  "tharak",
  "tharki",
  "tu chuda",
  "analritter",
  "arsch",
  "arschficker",
  "arschlecker",
  "arschloch",
  "bimbo",
  "bratze",
  "bumsen",
  "bonze",
  "dödel",
  "fick",
  "ficken",
  "flittchen",
  "fotze",
  "fratze",
  "hackfresse",
  "hure",
  "hurensohn",
  "ische",
  "kackbratze",
  "kacke",
  "kacken",
  "kackwurst",
  "kampflesbe",
  "kanake",
  "kimme",
  "MILF",
  "morgenlatte",
  "mufti",
  "muschi",
  "nackt",
  "nippel",
  "nutte",
  "onanieren",
  "orgasmus",
  "pimmel",
  "pimpern",
  "pinkeln",
  "pissen",
  "pisser",
  "popel",
  "poppen",
  "reudig",
  "rosette",
  "schabracke",
  "schlampe",
  "scheiße",
  "scheisser",
  "schiesser",
  "schnackeln",
  "schwanzlutscher",
  "schwuchtel",
  "tittchen",
  "titten",
  "vögeln",
  "vollpfosten",
  "wichse",
  "wichsen",
  "wichser",
  "noune",
  "osti",
  "criss",
  "crisse",
  "calice",
  "tabarnak",
  "viarge",
  "baiser",
  "bander",
  "bigornette",
  "bite",
  "bitte",
  "bloblos",
  "bordel",
  "bourré",
  "bourrée",
  "brackmard",
  "branlage",
  "branler",
  "branlette",
  "branleur",
  "branleuse",
  "brouter le cresson",
  "caca",
  "chatte",
  "chiasse",
  "chier",
  "chiottes",
  "clito",
  "con",
  "connard",
  "connasse",
  "conne",
  "couilles",
  "cramouille",
  "cul",
  "déconne",
  "déconner",
  "emmerdant",
  "emmerder",
  "emmerdeur",
  "emmerdeuse",
  "enculé",
  "enculée",
  "enculeur",
  "enculeurs",
  "enfoiré",
  "enfoirée",
  "étron",
  "fille de pute",
  "fils de pute",
  "folle",
  "foutre",
  "gerbe",
  "gerber",
  "gouine",
  "grande folle",
  "grogniasse",
  "gueule",
  "jouir",
  "la putain de ta mère",
  "MALPT",
  "ménage à trois",
  "merde",
  "merdeuse",
  "merdeux",
  "meuf",
  "nègre",
  "nique ta mère",
  "nique ta race",
  "palucher",
  "pédale",
  "pédé",
  "péter",
  "pipi",
  "pouffiasse",
  "pousse-crotte",
  "putain",
  "pute",
  "ramoner",
  "sac à foutre",
  "sac à merde",
  "salaud",
  "salope",
  "suce",
  "tapette",
  "tanche",
  "teuch",
  "tringler",
  "trique",
  "troncher",
  "trou du cul",
  "turlute",
  "zigounette",
  "zizi",
  "alfred nussi",
  "bylsiä",
  "haahka",
  "haista paska",
  "haista vittu",
  "hatullinen",
  "helvetisti",
  "hevonkuusi",
  "hevonpaska",
  "hevonperse",
  "hevonvittu",
  "hevonvitunperse",
  "hitosti",
  "hitto",
  "huorata",
  "hässiä",
  "juosten kustu",
  "jutku",
  "jutsku",
  "jätkä",
  "kananpaska",
  "koiranpaska",
  "kuin esterin perseestä",
  "kulli",
  "kullinluikaus",
  "kuppainen",
  "kusaista",
  "kuseksia",
  "kusettaa",
  "kusi",
  "kusipää",
  "kusta",
  "kyrpiintynyt",
  "kyrpiintyä",
  "kyrpiä",
  "kyrpä",
  "kyrpänaama",
  "kyrvitys",
  "lahtari",
  "lutka",
  "molo",
  "molopää",
  "mulkero",
  "mulkku",
  "mulkvisti",
  "muna",
  "munapää",
  "munaton",
  "mutakuono",
  "mutiainen",
  "naida",
  "nainti",
  "narttu",
  "neekeri",
  "nekru",
  "nuolla persettä",
  "nussia",
  "nussija",
  "nussinta",
  "paljaalla",
  "palli",
  "pallit",
  "paneskella",
  "panettaa",
  "panna",
  "pano",
  "pantava",
  "paska",
  "paskainen",
  "paskamainen",
  "paskanmarjat",
  "paskantaa",
  "paskapuhe",
  "paskapää",
  "paskattaa",
  "paskiainen",
  "paskoa",
  "pehko",
  "pentele",
  "perkele",
  "perkeleesti",
  "persaukinen",
  "perse",
  "perseennuolija",
  "perseet olalla",
  "perspano",
  "persvako",
  "pilkunnussija",
  "pillu",
  "pillut",
  "pipari",
  "piru",
  "pyllyvako",
  "reva",
  "ripsipiirakka",
  "runkata",
  "runkkari",
  "runkkaus",
  "runkku",
  "saatanasti",
  "suklaaosasto",
  "tavara",
  "toosa",
  "tuhkaluukku",
  "tumputtaa",
  "turpasauna",
  "tussu",
  "tussukka",
  "tussut",
  "vakipano",
  "vetää käteen",
  "viiksi",
  "vittu",
  "vittuilla",
  "vittuilu",
  "vittumainen",
  "vittuuntua",
  "vittuuntunut",
  "vitun",
  "vitusti",
  "vituttaa",
  "vitutus",
  "äpärä",
  "puta ka",
  "putang ina",
  "tang ina",
  "tangina",
  "burat",
  "bayag",
  "bobo",
  "nognog",
  "tanga",
  "ulol",
  "kantot",
  "anak ka ng puta",
  "jakol",
  "bugren",
  "bugri",
  "bugru",
  "ĉiesulino",
  "ĉiesulo",
  "diofek",
  "diofeka",
  "fek",
  "feken",
  "fekfikanto",
  "feklekulo",
  "fekulo",
  "fik",
  "fikado",
  "fikema",
  "fikfek",
  "fiki",
  "fikiĝi",
  "fikiĝu",
  "fikilo",
  "fikklaŭno",
  "fikota",
  "fiku",
  "forfiki",
  "forfikiĝu",
  "forfiku",
  "forfurzu",
  "forpisi",
  "forpisu",
  "furzulo",
  "kacen",
  "kaco",
  "kacsuĉulo",
  "kojono",
  "piĉen",
  "piĉo",
  "zamenfek",
  "aardappels afgieten",
  "achter het raam zitten",
  "afberen",
  "aflebberen",
  "afrossen",
  "afrukken",
  "aftrekken",
  "afwerkplaats",
  "afzeiken",
  "afzuigen",
  "een halve man en een paardekop",
  "anita",
  "asbak",
  "aso",
  "bagger schijten",
  "balen",
  "bedonderen",
  "befborstel",
  "beffen",
  "bekken",
  "belazeren",
  "besodemieterd zijn",
  "besodemieteren",
  "beurt",
  "boemelen",
  "boerelul",
  "boerenpummel",
  "bokkelul",
  "botergeil",
  "broekhoesten",
  "brugpieper",
  "buffelen",
  "buiten de pot piesen",
  "da's kloten van de bok",
  "de ballen",
  "de hoer spelen",
  "de hond uitlaten",
  "de koffer induiken",
  "de pijp uitgaan",
  "dombo",
  "draaikont",
  "driehoog achter wonen",
  "drol",
  "drooggeiler",
  "droogkloot",
  "een beurt geven",
  "een nummertje maken",
  "een wip maken",
  "eikel",
  "engerd",
  "flamoes",
  "flikken",
  "flikker",
  "gadverdamme",
  "galbak",
  "gat",
  "gedoogzone",
  "geilneef",
  "gesodemieter",
  "godverdomme",
  "graftak",
  "gras maaien",
  "gratenkut",
  "greppeldel",
  "griet",
  "hoempert",
  "hoer",
  "hoerenbuurt",
  "hoerenloper",
  "hoerig",
  "hufter",
  "huisdealer",
  "johny",
  "kanen",
  "kettingzeug",
  "klaarkomen",
  "klerebeer",
  "klojo",
  "klooien",
  "klootjesvolk",
  "klootoog",
  "klootzak",
  "kloten",
  "knor",
  "kont",
  "kontneuken",
  "krentekakker",
  "kut",
  "kuttelikkertje",
  "kwakkie",
  "liefdesgrot",
  "lul",
  "lul-de-behanger",
  "lulhannes",
  "lummel",
  "mafketel",
  "matennaaier",
  "matje",
  "mof",
  "muts",
  "naaien",
  "naakt",
  "neuken",
  "neukstier",
  "nicht",
  "oetlul",
  "opgeilen",
  "opkankeren",
  "oprotten",
  "opsodemieteren",
  "op z'n hondjes",
  "op z'n sodemieter geven",
  "opzouten",
  "ouwehoer",
  "ouwehoeren",
  "ouwe rukker",
  "paal",
  "paardelul",
  "palen",
  "penoze",
  "piesen",
  "pijpbekkieg",
  "pijpen",
  "pik",
  "pleurislaaier",
  "poep",
  "poepen",
  "poot",
  "portiekslet",
  "pot",
  "potverdorie",
  "publiciteitsgeil",
  "raaskallen",
  "reet",
  "reetridder",
  "reet trappen, voor zijn",
  "remsporen",
  "reutelen",
  "rothoer",
  "rotzak",
  "rukhond",
  "rukken",
  "schatje",
  "schijt",
  "schijten",
  "schoft",
  "schuinsmarcheerder",
  "slempen",
  "slet",
  "sletterig",
  "slik mijn zaad",
  "snol",
  "spuiten",
  "standje",
  "standje-69",
  "stoephoer",
  "stootje",
  "stront",
  "sufferd",
  "tapijtnek",
  "teef",
  "temeier",
  "teringlijer",
  "toeter",
  "tongzoeng",
  "triootjeg",
  "trottoir prostituée",
  "trottoirteef",
  "vergallen",
  "verkloten",
  "verneuken",
  "viespeuk",
  "vingeren",
  "vleesroos",
  "voor jan lul",
  "voor jan-met-de-korte-achternaam",
  "watje",
  "welzijnsmafia",
  "wijf",
  "wippen",
  "wuftje",
  "zaadje",
  "zakkenwasser",
  "zeiken",
  "zeiker",
  "zuigen",
  "zuiplap",
  "bøsserøv",
  "fisse",
  "fissehår",
  "hestepik",
  "kussekryller",
  "lort",
  "luder",
  "pikhår",
  "pikslugeri",
  "piksutteri",
  "pis",
  "røv",
  "røvhul",
  "røvskæg",
  "røvspræke",
  "buzna",
  "čumět",
  "čurák",
  "do piče",
  "do prdele",
  "dršťka",
  "držka",
  "flundra",
  "hajzl",
  "hovno",
  "chcanky",
  "jebat",
  "kokot",
  "kokotina",
  "kunda",
  "mamrd",
  "mrdat",
  "mrdka",
  "oslošoust",
  "prcat",
  "prdel",
  "prdelka",
  "zkurvit",
  "zkurvysyn",
  "zmrd",
};

const inappropriateImagePlaceholder = '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAGyAzQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD+7Ik5PJ6nufWkyfU/maG6n6n+dJQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUALk+p/M0ZPqfzNJRQAuT6n8zRk+p/M0lFAC5PqfzNGT6n8zSUUASoSQcnPP+FFCdD9f6CigCNup+p/nSUrdT9T/OkoAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCVOh+v9BRQnQ/X+gooAjbqfqf50lK3U/U/wA6SgAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoorz/AOIvxL8L/DDQn1vxLdlA5aLT9Ot9smoapcqAfIs4WZQdoKmaeRkggUgyyKWRWAPQKK/LXxf+2H8StYupR4Xj03wnp4c/Z1jtLbVdRaPPH2m51KGe1ZiOSILGALkrliN54n/hqP45f9Dr/wCW/wCGP/lNQB+wFFfj/wD8NR/HL/odf/Lf8Mf/ACmo/wCGo/jl/wBDr/5b/hj/AOU1AH7AUV+P/wDw1H8cv+h1/wDLf8Mf/Kaj/hqP45f9Dr/5b/hj/wCU1AH7AUV+P/8Aw1H8cv8Aodf/AC3/AAx/8pqP+Go/jl/0Ov8A5b/hj/5TUAfsBRX4/wD/AA1H8cv+h1/8t/wx/wDKaj/hqP45f9Dr/wCW/wCGP/lNQB+wFFfj/wD8NR/HL/odf/Lf8Mf/ACmo/wCGo/jl/wBDr/5b/hj/AOU1AH7AUV+P/wDw1H8cv+h1/wDLf8Mf/Kaj/hqP45f9Dr/5b/hj/wCU1AH7AUV+P/8Aw1H8cv8Aodf/AC3/AAx/8pqP+Go/jl/0Ov8A5b/hj/5TUAfsBRX4/wD/AA1H8cv+h1/8t/wx/wDKaj/hqP45f9Dr/wCW/wCGP/lNQB+wFFfj/wD8NR/HL/odf/Lf8Mf/ACmo/wCGo/jl/wBDr/5b/hj/AOU1AH7AUV+P/wDw1H8cv+h1/wDLf8Mf/Kaj/hqP45f9Dr/5b/hj/wCU1AH7AUV+P/8Aw1H8cv8Aodf/AC3/AAx/8pqP+Go/jl/0Ov8A5b/hj/5TUAfsBRX4/wD/AA1H8cv+h1/8t/wx/wDKaj/hqP45f9Dr/wCW/wCGP/lNQB+wFFfj/wD8NR/HL/odf/Lf8Mf/ACmo/wCGo/jl/wBDr/5b/hj/AOU1AH7AUV+P/wDw1H8cv+h1/wDLf8Mf/Kaj/hqP45f9Dr/5b/hj/wCU1AH7AUV+P/8Aw1H8cv8Aodf/AC3/AAx/8pqP+Go/jl/0Ov8A5b/hj/5TUAfsBRX4/wD/AA1H8cv+h1/8t/wx/wDKaj/hqP45f9Dr/wCW/wCGP/lNQB+wFFfj/wD8NR/HL/odf/Lf8Mf/ACmo/wCGo/jl/wBDr/5b/hj/AOU1AH7AUV+P/wDw1H8cv+h1/wDLf8Mf/Kaj/hqP45f9Dr/5b/hj/wCU1AH7AUV+P/8Aw1H8cv8Aodf/AC3/AAx/8pqP+Go/jl/0Ov8A5b/hj/5TUAfsBRX4/wD/AA1H8cv+h1/8t/wx/wDKaj/hqP45f9Dr/wCW/wCGP/lNQB+wFFfj/wD8NR/HL/odf/Lf8Mf/ACmo/wCGo/jl/wBDr/5b/hj/AOU1AH7AUV+P/wDw1H8cv+h1/wDLf8Mf/Kaj/hqP45f9Dr/5b/hj/wCU1AH7AUV+P/8Aw1H8cv8Aodf/AC3/AAx/8pqP+Go/jl/0Ov8A5b/hj/5TUAfsBRX4/wD/AA1H8cv+h1/8t/wx/wDKaj/hqP45f9Dr/wCW/wCGP/lNQB+wFFfj/wD8NR/HL/odf/Lf8Mf/ACmo/wCGo/jl/wBDr/5b/hj/AOU1AH7AUV+P/wDw1H8cv+h1/wDLf8Mf/Kaj/hqP45f9Dr/5b/hj/wCU1AH7AUV+P/8Aw1H8cv8Aodf/AC3/AAx/8pqP+Go/jl/0Ov8A5b/hj/5TUAfsBRX4/wD/AA1H8cv+h1/8t/wx/wDKap7b9qj43wTRyyeLYbpEYFrefQPDwhlH91zb6XBMFPcxyxt6MKAP15or4v8AhF+1vpfiq9tfD/j6ztPD2q3TpBaazaO66JdTudqRXUc7yS6bJI2FSVp57VnJ3vbDaD9oAggEEEEZBHIIPQg9waACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCVOh+v8AQUUJ0P1/oKKAI26n6n+dJSt1P1P86SgAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigBCQoJPAAJJ9gMmvxf+OHxHvPiV4+1fVmnd9HsbibTfD1tuPkwaXayskUyJnAlvmDXlw3Lb5vLDGOKMD9ldRYpp9+6nDLZ3TAjqCsDkH8CK/A6T/WSf77f+hGgBlFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAAkHIOCOQR1B9a/V79lL4j3fjfwDLo+rTvc6z4Ont9NkuJGLy3OlXMcj6TNM7HLSxrb3VkWOS8dnHI7NI7mvyhr73/YbYi8+IqZ+Vrbw2xHYlZdZAP4B2/M0AfoTRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBKnQ/X+gooTofr/QUUARt1P1P86Slbqfqf50lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFHVP+QbqP8A143f/pPJX4ISf6yT/fb/ANCNfvfqn/IN1H/rxu//AEnkr8EJP9ZJ/vt/6EaAGUUUUAFFFeh+CPhV48+I0WoTeDdCbWItLkgivmF/pdl5D3KytApGoXtoZN6wyHMQcLt+YjIyAeeUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+/8MwfHH/oSH/8AB74a/wDlxR/wzB8cf+hIf/we+Gv/AJcUAeBUV77/AMMwfHH/AKEh/wDwe+Gv/lxR/wAMwfHH/oSH/wDB74a/+XFAHgVFe+H9mD44gEnwQ+ACT/xPfDR4HsNYzXg8sTwSyQyrtkido5FyDtdGKsMqSDggjIJB7GgCOiiigAr71/Yc/wCP74if9enhz/0dq9fBVfev7Dn/AB/fET/r08Of+jtXoA/QuiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCVOh+v9BRQnQ/X+gooAjbqfqf50lK3U/U/zpKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAKOqf8g3Uf+vG7/wDSeSvwQk/1kn++3/oRr979U/5Buo/9eN3/AOk8lfghJ/rJP99v/QjQAyiiigAr9Ef2Hf8AkE/ED/r/ANA/9EapX53V+iP7Dv8AyCfiB/1/6B/6I1SgD7vooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAa/3G/wB1v5GvwQ1X/kJ6h/1+3X/o56/e9/uN/ut/I1+CGq/8hPUP+v26/wDRz0AUKKKKACvvX9hz/j++In/Xp4c/9HavXwVX3r+w5/x/fET/AK9PDn/o7V6AP0LooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAlTofr/QUUJ0P1/oKKAI26n6n+dJSt1P1P86SgAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCjqn/IN1H/rxu//AEnkr8EJP9ZJ/vt/6Ea/e/VP+QbqP/Xjd/8ApPJX4ISf6yT/AH2/9CNADKKKKACv0R/Yd/5BPxA/6/8AQP8A0RqlfndX6I/sO/8AIJ+IH/X/AKB/6I1SgD7vooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAa/3G/3W/ka/BDVf+QnqH/X7df8Ao56/e9/uN/ut/I1+CGq/8hPUP+v26/8ARz0AUKKKKACvvX9hz/j++In/AF6eHP8A0dq9fBVfev7Dn/H98RP+vTw5/wCjtXoA/QuiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCVOh+v9BRQnQ/X+gooAjbqfqf50lK3U/U/wA6SgAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCjqn/IN1H/AK8bv/0nkr8EJP8AWSf77f8AoRr979U/5Buo/wDXjd/+k8lfghJ/rJP99v8A0I0AMooooAK/RH9h3/kE/ED/AK/9A/8ARGqV+d1foj+w7/yCfiB/1/6B/wCiNUoA+76KKKACiiigAooooAKKKKACiiigAoork/FXjvwf4ItftnirxDpmixMrNFHdXA+1XAX7wtbKISXl0w7rbwSEdxQB1lFfHHiP9tHwBpzyQ+HtD13xE6EhbiUQaPYy/wB0xyTG6vAD382wjIBGFY5FeaXP7cOrs5Np4A06FOy3GuXNwwGe7R6fbAnHog+lAH6JUV+fmn/txSb1XVfh8hjJG6Ww19ldR3Ihn0t1c+gM0Y969p8J/tZfCfxI8Vvf3moeFbuQqgXXbUCzMhIGFv7GS7gjjGc+befZF4OccZAPpqiqdhqFhqtpDf6Ze2mo2Vwgkt7yyuIrq2mQ9Hingd4pFPqrEVcoAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAGv9xv91v5GvwQ1X/kJ6h/1+3X/AKOev3vf7jf7rfyNfghqv/IT1D/r9uv/AEc9AFCiiigAr71/Yc/4/viJ/wBenhz/ANHavXwVX3r+w5/x/fET/r08Of8Ao7V6AP0LooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAlTofr/QUUJ0P1/oKKAI26n6n+dJSt1P1P8AOkoAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAo6p/yDdR/wCvG7/9J5K/BCT/AFkn++3/AKEa/e/VP+QbqP8A143f/pPJX4ISf6yT/fb/ANCNADKKKKACv0R/Yd/5BPxA/wCv/QP/AERqlfndX6I/sO/8gn4gf9f+gf8AojVKAPu+iiigAooooAKKKKACiiigApksscMck00iRRRI0kksjKkccaAs7u7EKqKoJZmIAAJJAp9fm7+1D8e5tZvb34ceEL1o9FsZWtvEmpW0hU6reRMVl0yGRDn+z7VwUuSDi8uFKf8AHvEDcAHW/Gj9rb7HNd+Gvhc8U00Ze3vPFssazQpICVddEt5A0U205A1C4WSFsE20EimO5r4G1bWdW16+n1PWtRvdV1C5cvPeX9zLdXErH+9LMzuQBwq52qoCqAABWbRQAUUUUAFFFFAHoXgL4peNvhtfre+F9ZuLaIur3Wlzs1xpN8ARlbuwkbyXZlGwTxiO6iUnyZ4yc1+nnwY/aC8NfFaBNOnEeh+L4Yd9zos0oMV6EH7y50id8G4ixl5LZwLq3G7IliTz2/IGrunajfaTfWup6ZdT2N/Yzx3Npd20jRT288TB45I5EIZWVgCCD7HigD986K+d/wBnv41wfFbw81lqjxQeMtDijTVoF2ouo25xHFrFrEMAJK2I7yJBtt7kggJFPAD9EUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUANf7jf7rfyNfghqv8AyE9Q/wCv26/9HPX73v8Acb/db+Rr8ENV/wCQnqH/AF+3X/o56AKFFFFABX3r+w5/x/fET/r08Of+jtXr4Kr71/Yc/wCP74if9enhz/0dq9AH6F0UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUASp0P1/oKKE6H6/wBBRQBG3U/U/wA6Slbqfqf50lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFHVP+QbqP/Xjd/wDpPJX4ISf6yT/fb/0I1+9+qf8AIN1H/rxu/wD0nkr8EJP9ZJ/vt/6EaAGUUUUAFfoj+w7/AMgn4gf9f+gf+iNUr87q/RH9h3/kE/ED/r/0D/0RqlAH3fRRRQAUUUUAFFFFABRRRQB8/ftIfE1/hx8Prr+zp/J8ReJGk0fRmRts1srxk6hqUeCGBs7ZtkTqcx3dxasQQCK/IJmZ2Z2JZmJZmJySxOSST1JPJNfU/wC154uk1/4ovoUcpax8I6da6dHGGzH9vvY01C/mA6CQ+fbWkmP+fNR1BJ+VqACiiigAooooAKKKKACiiigDufhx451L4deMdG8Vaa7brC5QXtsGKpfabKRHfWUvYrPAXCMwbyphHMo3xoR+2uj6tZa7pOm61psy3Gn6rY2uoWcy9JLa7hSeJvZtjgMp5VgVPINfgjX6n/sfeLpNe+Gk+g3MpkufCWqy2UQYlnGmagDfWZYkk4W4a/gjHRYoY1XAG1QD6xooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigBr/AHG/3W/ka/BDVf8AkJ6h/wBft1/6Oev3vf7jf7rfyNfghqv/ACE9Q/6/br/0c9AFCiiigAr71/Yc/wCP74if9enhz/0dq9fBVfev7Dn/AB/fET/r08Of+jtXoA/QuiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCVOh+v9BRQnQ/X+gooAjbqfqf50lK3U/U/zpKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAKOqf8g3Uf+vG7/wDSeSvwQk/1kn++3/oRr979U/5Buo/9eN3/AOk8lfghJ/rJP99v/QjQAyiiigAr9Ef2Hf8AkE/ED/r/ANA/9EapX53V+iP7Dv8AyCfiB/1/6B/6I1SgD7vooooAKKKKACiiigAoPAJ9KKQ8g/Q0Afh18T9SfV/iN441F2LfavFWuyISSdsP9pXKwIM5OI4QiD2UVwtdR43he28Z+LLeT/WQeI9ahcHIIePUblGBBwQcg5B5rl6ACiiigAooooAKKKKACiiigAr7g/Yi1J4vFPjTSAx8u80Ky1BkzwX02/8As6Nj1A1Rx/wL3r4fr7N/YngdviD4nuQG8uHwhNCxH3d9xrGkugPuRbOR9DQB+mdFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUANf7jf7rfyNfghqv/IT1D/r9uv/AEc9fve/3G/3W/ka/BDVf+QnqH/X7df+jnoAoUUUUAFfev7Dn/H98RP+vTw5/wCjtXr4Kr71/Yc/4/viJ/16eHP/AEdq9AH6F0UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUASp0P1/oKKE6H6/0FFAEbdT9T/OkpW6n6n+dJQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBR1T/AJBuo/8AXjd/+k8lfghJ/rJP99v/AEI1+9+qf8g3Uf8Arxu//SeSvwQk/wBZJ/vt/wChGgBlFFFABX6I/sO/8gn4gf8AX/oH/ojVK/O6v0R/Yd/5BPxA/wCv/QP/AERqlAH3fRRRQAUUUUAFFFFABRRRQB+Nn7RXh5/Dnxh8Z25jKQ6lqP8Abts2MLLHrUaahK6diFupriE44DxOBwBXiVfor+2h4AkvdN0P4h2EBeTSsaHrjIuStjcytNply5A4jgvJLi2djkmS+t1GFU1+dVABRRRQAUUUUAFFFFABRRRQAV+if7EXh54dI8a+KJY8JfX2naLaSMMH/iXwzXl4FPUq5v7ME9N0ZGcg4/PK3t5ru4gtbaJ5ri4ljgghiUvJLLKwSOONFBZ3dmCqoBLEgAZNfth8IfBC/Dz4eeHPDDKovbazF1qrLg79Wvibq+G8f6xYZpDbRP3hgj4AGAAelUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQA1/uN/ut/I1+CGq/8hPUP+v26/8ARz1+97/cb/db+Rr8ENV/5Ceof9ft1/6OegChRRRQAV96/sOf8f3xE/69PDn/AKO1evgqvvX9hz/j++In/Xp4c/8AR2r0AfoXRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBKnQ/X+gooTofr/QUUARt1P1P86Slbqfqf50lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFHVP8AkG6j/wBeN3/6TyV+CEn+sk/32/8AQjX736p/yDdR/wCvG7/9J5K/BCT/AFkn++3/AKEaAGUUUUAFfoj+w7/yCfiB/wBf+gf+iNUr87q/RH9h3/kE/ED/AK/9A/8ARGqUAfd9FFFABRRRQAUUUUAFFFFAGRr2h6b4l0bU9A1e3W603VrOexvIWA+aGdChZD1SWMkSRSLh4pVSRCGUEfjD8VvhrrHwu8W33h7UkeS0Lvc6NqWwrDqemO7CCdCPlWZADFdQgkw3COoLRmOR/wBta80+KXwu8O/FXw5Lomtx+TdQ75tH1eJFN3pV4y4EsZOPMt5cKl1aswSeMDBSZIpYwD8SqK9H+JPws8WfC/WZNL8RWLi3keT+zdYt1d9M1SBTxLbXG0BZApBltpdlxASPMjCsjN5xQAUUUUAFFFFABRR16V9X/Aj9mvWPH1zaeJPF1vc6P4MiZJ4opFaC/wDEIBDLFaKwDwae4x5t+wHmIfLs97s00AB1n7Jnwal1rVoviV4htGXR9Imb/hG4J0wupatGSp1BVcfNa6Y4JhcDD34Qo+bSVT+ktU9P0+y0qxtdN021gsrCxgitbS0to1igt7eFAkUUUagKqIoAAA9zk81coAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAa/3G/3W/ka/BDVf+QnqH/X7df+jnr973+43+638jX4Iar/AMhPUP8Ar9uv/Rz0AUKKKKACvvX9hz/j++In/Xp4c/8AR2r18FV96/sOf8f3xE/69PDn/o7V6AP0LooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAlTofr/AEFFCdD9f6CigCNup+p/nSUrdT9T/OkoAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAo6p/wAg3Uf+vG7/APSeSvwQk/1kn++3/oRr979U/wCQbqP/AF43f/pPJX4ISf6yT/fb/wBCNADKKKKACv0R/Yd/5BPxA/6/9A/9EapX53V+iP7Dv/IJ+IH/AF/6B/6I1SgD7vooooAKKKKACiiigAooooAKKKKAMbX/AA7ofinTLjRvEOl2er6ZcqVltL2FZY84IWSMn54ZkzmKeFo5omw0bqwBr4h+IP7F0E8k9/8ADnXFtAxZxoOvNI8CEknZaarCksyoB8scV3bSsTjzLzGSPveigD8XPEfwH+LXhiR11DwRrU8SE/6VpNv/AGzasgOBIZdLN2IkYcjz/KYDh1VuK82uNE1m0cx3Wk6jbSA4KXFlcwuD6FZI1OfbFfvZTdq/3V/If4UAfhHp/hHxVqrrHpfhrXtRkY4VLHSb+6dj6BYIHJ/AV7P4U/Zc+LvieSJp9CTw1ZOV3XniK4SzZFOC3/EvjE+p7wpyoezRC3ymReSP12CqOigfQAUtAHyz8M/2UvAvgmS31TxA58Za5CUkja/gSHRrSVcENb6XulFw6HIEl9NcISFkjt4HHH1KqqihUUKqgKqqAqqoGAABgAAcAAYA6UtFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFcd4m+IXgjwahbxN4o0XR3C7xbXV9CL11wTmKwjZ7ybgceVA+eMckV4PrX7YPwk0x3jsD4h19lyFk07S1t4GYHHL6rcafMq/wC0Ldjj+GgD6por4bn/AG3/AA4rkW3gfWZUzw02qWcDkepRLecD6bzV2w/bb8Fyuo1Lwj4jtEJwz2c+nXxUZ67ZptPzjuNw/oQD7XorwXwz+0t8H/E7xwR+KE0a6k2gW3iG3l0sAtgANeSB9NBzxj7b156c17nbXNteQx3NpcQXVvMgkint5UmhlRhlXjljZkdWHIZWIPY0AT0UUUAFFFFABRRRQAUUUUAFFFFADX+43+638jX4Iar/AMhPUP8Ar9uv/Rz1+97/AHG/3W/ka/BDVf8AkJ6h/wBft1/6OegChRRRQAV96/sOf8f3xE/69PDn/o7V6+Cq+9f2HP8Aj++In/Xp4c/9HavQB+hdFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAEqdD9f6CihOh+v8AQUUARt1P1P8AOkpW6n6n+dJQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBR1T/kG6j/143f8A6TyV+CEn+sk/32/9CNfvfqn/ACDdR/68bv8A9J5K/BCT/WSf77f+hGgBlFFFABX6I/sO/wDIJ+IH/X/oH/ojVK/O6v0R/Yd/5BPxA/6/9A/9EapQB930UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUdOtch408d+Fvh/o8ut+KdVg020QMII2O+7vpgMi2sbVczXM7cfKi7YwfMmeOJWdfzW+Lf7Uvi3x011pHhdrjwn4XcvEUt5dutalCflzfX0LA28Ui8tZ2TKm1minuLtCMAH2x8TP2j/h58OTcWH2z/hJPEUW5f7F0aSOUQTDI2ajqHzWtjtYbZIgbi8jyCbQjmvg7x7+1F8TvGjTW1jqI8JaRIWVbDQGeC6aM5AFzqzf6fI+CVf7PJaQSA4a36V84sxYlmJZickk5JJ7kmkoAmnuJ7qWSe5mluJpXaSSWaRpJJHY5Z3dyWZmJyWJJJ5JqGiigAooooAK9E8DfFXx38O7pLjwvr95aQBw82mTSG60m65BYT6fOXtyzgbTNGkdwik+VNGxzXndFAH6sfCD9qLwv4/e20PxMkHhbxTLtihWSY/2NqsxwoWyupm3W1xKxwlldsSxKxwXNxI2wfVHXpX4AAlSCCQQcgjggjoQa+6P2e/2m59NksvBPxGvnuNMcx2ujeJrqQvPpzEhIrPVpnJaWxPCQ3rkyWhws7PakPbAH6L0U1HWRVdGV0dVdHUhlZWAKsrDIKsCCCCQQcinUAFFFFABRRRQAUUUUANf7jf7rfyNfghqv/IT1D/r9uv8A0c9fve/3G/3W/ka/BDVf+QnqH/X7df8Ao56AKFFFFABX3r+w5/x/fET/AK9PDn/o7V6+Cq+9f2HP+P74if8AXp4c/wDR2r0AfoXRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBKnQ/X+gooTofr/QUUARt1P1P86Slbqfqf50lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFHVP+QbqP8A143f/pPJX4ISf6yT/fb/ANCNfvfqn/IN1H/rxu//AEnkr8EJP9ZJ/vt/6EaAGUUUUAFfoj+w7/yCfiB/1/6B/wCiNUr87q/RH9h3/kE/ED/r/wBA/wDRGqUAfd9FFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAV4J8aPj14c+E9i9ohi1jxdcw7rDQopQBbq4Oy91aRCWtbUH5o4gPtF0RtiVI988XKfH/wDaIsPhtbTeGvDMlvqHja6hIc5Wa18OxSL8tzeLyst+6sHtbJuFBW4uh5XlQ3H5aapqmo61qF3qurXlxqGo30z3F3eXUrTTzzSHLPJI5LEk8AdFACgAACgDovG/jzxP8Qtbn13xRqUt/dyErDFkpZ2MGcpa2NsD5dvbp2VBudsySvJKzyNx1FFABRRRQAUUUUAFFFFABRRRQAUUUUAfoB+yx8epGez+GXjG9LhgsHhLVbqX5lI4TQrmVzlgw40x3b5SPsQJDWqL+gFfgHDNLbyxTwSPFNDIksUsbMkkckbB0dHUhldGAZWUgggEHNfrt+zp8Xk+KHhBbfU50Pi3w6kNnrKEhXvoSu201dE7i6VDHdbRiO8jkO1I5oQQD6GooooAKKKKACiiigBr/cb/AHW/ka/BDVf+QnqH/X7df+jnr973+43+638jX4Iar/yE9Q/6/br/ANHPQBQooooAK+9f2HP+P74if9enhz/0dq9fBVfev7Dn/H98RP8Ar08Of+jtXoA/QuiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCVOh+v9BRQnQ/X+gooAjbqfqf50lK3U/U/zpKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAKOqf8g3Uf+vG7/8ASeSvwQk/1kn++3/oRr979U/5Buo/9eN3/wCk8lfghJ/rJP8Afb/0I0AMooooAK/RH9h3/kE/ED/r/wBA/wDRGqV+d1foj+w7/wAgn4gf9f8AoH/ojVKAPu+iiigAooooAKKKKACiiigAooooAKK5TXvHfgzwvkeIvFWgaM4GRDqGq2dvcsMZ/d2zzC4kJHICRsSOcYrze4/aT+Cdq5STxzaOwOP9H0zXLpe/Ie20yVCOOobHT1FAHudFeIWv7R/wVu2VIvHVihbgfabDWLNR9Wu9OhUfUkDvnHNd7o3xD8B+IWVNE8Y+G9TlfG23tNZsJbnJ6A2wn89SfRowfagDsqKQEEZBBHqDkfmKWgAooooAKKKKACiiigAooooAKKKKACvlf9oj9oC1+G9jL4Y8MzRXPje/g+aRdksPh22mX5bu5U7lbUJEIaytHGEBW6uFMXlRXG98fvjnY/CrRTp2lyQXnjXVYGGm2ZKyJpkD7kOrX6Z4RGBFpA/N1MpJUwRTEfkvqWpX+sX93qmp3U99qF/cS3V3d3EjSzTzzMXkkkdiSWZiT1wOgwABQBFeXl3qF3cX19cTXd5dzSXFzdXEjSzzzysXllllcs7yO7FmZiSSSSarUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFelfCb4h3/wy8baT4mtTI9pHKLTWLNGwL/SLllW8tyCQpkVQtxbFvlS6hhc5CkHzWigD989N1Gz1fTrHVdOnS6sNStLe+s7mI7o57a6iWaGVD6PG6sM4IzggHirtfE/7HPxJbWNA1D4e6ncF77w9u1DRDIwLy6LcSgXNsmSWYafeyBxn7sN7HGgEcGB9sUAFFFFABRRRQA1/uN/ut/I1+CGq/wDIT1D/AK/br/0c9fve/wBxv91v5GvwQ1X/AJCeof8AX7df+jnoAoUUUUAFfev7Dn/H98RP+vTw5/6O1evgqvvX9hz/AI/viJ/16eHP/R2r0AfoXRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBKnQ/X+gooTofr/AEFFAEbdT9T/ADpKVup+p/nSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAUdU/5Buo/9eN3/AOk8lfghJ/rJP99v/QjX736p/wAg3Uf+vG7/APSeSvwQk/1kn++3/oRoAZRRRQAV+iP7Dv8AyCfiB/1/6B/6I1Svzur9Ef2Hf+QT8QP+v/QP/RGqUAfd9FFFABRRRQAUUUUAFFFfHHx+/aZt/Bhu/B/gSaC98UgNBqWrjZPZ6Axyrwwj5o7rVU6MrBoLN8CZZZg8MYB7N8Ufjd4J+FVsV1m8N9rksZez8O6c0cuozAg7JbnLCOwtSf8AlvcsrOof7PFcOhSvzu+IX7T/AMSvG8k9tY6g3hLRHLKmnaFLJBcvEegvNWGy9ncjKuIWtbaRThravn7UNRv9WvbnUdTvLm/v7yV57q7u5pJ7ieVzl5JZZGZ3Zj1JJqlQBLNPNcSPNcSyTSyMzySSu0ju7HLOzMSzMxJJYkkkkk5qKiigApQzLyrFT6gkfypKKAPSfCvxe+JPgx4z4f8AF+s2sEWNthPctf6bgdR/Z18LizGRwWWEOB0YEAj6n8FftrajAYrXx74agvovlV9V8PP9lulUYBeTTbuR7a4duSxiu7JB2jNfB9FAH7a+CPi/8PPiEiDw14ksp71ly2k3b/YNWQgZcfYLry5pgnRpbYTwZ6SkEE+l1+AcU0sEiSwySQyxsHjkidkdHU5VkdSGVlIBVgQQRkEGvonwH+1D8UPBYhtbrUl8V6TFtX7D4gMlzcJEMArb6orLfowUBYxPNdQRjG2DHBAP1zor5T8Fftd/DXxGsVv4hF74O1F9qsL5GvtLaRscRajZxF0UHO57yztI1AyXNfS2ka9omv2qX2h6vpusWb423Om3tvewnPQeZbySKG65UkMCCCMg0Aa1FFFABRRRQAV4f8bfjVo3wk0JmDQX/irUInXRNF3gkEhlGo6gqsHi0+Bgf7r3Uq+RCVHmyw8/8Z/2jPDHwztrnStJltvEHjNkZItMglElppcjAhZ9Ymib92UJDiwjcXUvyh/s8Ticflb4m8Ta34v1q+8QeIb+bUdU1CUyz3EzZwOiQxIMJDBCgEcMMarHFGqoigACgCPxD4h1fxVrOoa/r17NqGq6ncPcXVzM2WZ24VEUYWOGJAsUMMarHFEiRxqqKAMWiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAPQPhd42ufh7468PeKYGcw2F9GuoQp1udLuc2+o2+3O1me1klMW7ISdYpcbo1x+3Fnd29/aWt9aSpPa3lvDdW08Z3RzW9xGssMqN3WSN1ZT3BFfgPX6x/soeOT4s+GNvpF1N5mp+Drj+xZQzZkbTWXz9IlIzxGkBksI+nFgevUgH07RRRQAUUUUANf7jf7rfyNfghqv/IT1D/r9uv8A0c9fve/3G/3W/ka/BDVf+QnqH/X7df8Ao56AKFFFFABX3r+w5/x/fET/AK9PDn/o7V6+Cq+9f2HP+P74if8AXp4c/wDR2r0AfoXRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBKnQ/X+gooTofr/QUUARt1P1P86Slbqfqf50lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFHVP+QbqP8A143f/pPJX4ISf6yT/fb/ANCNfvfqn/IN1H/rxu//AEnkr8EJP9ZJ/vt/6EaAGUUUUAFfoj+w7/yCfiB/1/6B/wCiNUr87q/RH9h3/kE/ED/r/wBA/wDRGqUAfd9FFFABRRRQAUUV4R8fPjBbfCjwm8lo8UvirWlltPD9o21/KYKBcarcRnrb2KupRWBE9y8MONhlZADy39pf9oD/AIQ23n8CeDrwf8JTeQ7dX1OBwToFpMmRBC6n5dVuY23Bgd1lAyyjE0sTR/mXJI8rvJI7SSSMzu7sWd3YkszMSSzMSSSSSTyanvr681O8utQv7ma7vb2eW6u7q4dpZri4ndpJZZZHJZ3kdmZmJJJJNVaACiiigAooooAKKKKACiiigAooooAK0tM1nV9FuFu9H1TUNLukxsudPvLiznXByNstvJHIOeeGFZtFAHumi/tJ/GbQ1SKHxnd30KADytXtrHVWcD+/c3ttNeE+pFwGPcmvQbX9sz4r26hZrHwhekdXudKv0Y/X7Jq1qvPU4Ue2BgD5KooA+u5v20PipKpWPSfBduSMb4dM1ZmB9R5+uTLn6qRx0rzrxR+0l8XvFVtLZXXiiTTLKZSsttoVvBpRdWBDK13bIL8oykq0ZuzG65DKcnPhNFADnd5GZ5HZ3clmd2LMzE5JZiSSSTkknJNNoooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK+p/2RvGR8OfE9NDnlKWHjCxm0tlZsRjUrYNeabK3q5aKeyiH96+x7j5YrV0LVrrQda0nW7F9l5pGo2WpWr5I2z2VxHcRE45xvjXI7jIoA/euisvQ9Wtte0XSdcs23WmsabZanbNkHMF9bR3MWSOM7JAD756VqUAFFFFADX+43+638jX4Iar/wAhPUP+v26/9HPX73v9xv8Adb+Rr8ENV/5Ceof9ft1/6OegChRRRQAV96/sOf8AH98RP+vTw5/6O1evgqvvX9hz/j++In/Xp4c/9HavQB+hdFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAEqdD9f6CihOh+v9BRQBG3U/U/zpKVup+p/nSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAUdU/5Buo/9eN3/wCk8lfghJ/rJP8Afb/0I1+9+qf8g3Uf+vG7/wDSeSvwQk/1kn++3/oRoAZRRRQAV+iP7Dv/ACCfiB/1/wCgf+iNUr87q/RH9h3/AJBPxA/6/wDQP/RGqUAfd9FFFABRRRQBk67rem+G9G1LXtYuUtNM0mznvryd/wCCGBC7BV6vI+AkUa5eWRljQFmAP4tfFP4ian8TvGWp+JtQaRIJZDb6TYs5ZNO0qF2FpaoM7d+0mW4dQBLcyzSgDfgfW37Y/wAUWaWz+F+kXBCRC31XxQ0T8PIwEumaZJjn92m3UZ0bILSWLAho2FfAlABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfrf+yn4nPiL4Q6TbSyeZdeG76+0GYk5byonW9sgRkkKllfQQIehEJA5Vq+ka/O/9iLxEY9V8aeFZJMrd2FjrtrGT917Gc2N46juZFv7MNjnEKnpmv0QoAKKKKAGv9xv91v5GvwQ1X/kJ6h/1+3X/o56/e9/uN/ut/I1+CGq/wDIT1D/AK/br/0c9AFCiiigAr71/Yc/4/viJ/16eHP/AEdq9fBVfev7Dn/H98RP+vTw5/6O1egD9C6KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAJU6H6/wBBRQnQ/X+gooAjbqfqf50lK3U/U/zpKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAKOqf8AIN1H/rxu/wD0nkr8EJP9ZJ/vt/6Ea/e/VP8AkG6j/wBeN3/6TyV+CEn+sk/32/8AQjQAyiiigAr9Ef2Hf+QT8QP+v/QP/RGqV+d1foj+w7/yCfiB/wBf+gf+iNUoA+76KKKACiiigD57179mP4W+JdZ1PX9Ytdbu9T1e8nvr2dtaul3zzuXYIgG2ONMhIokASKNVRAFUAZH/AAyP8Gv+gZrP/g7uv8K+m6KAPmT/AIZH+DX/AEDNZ/8AB3df4Uf8Mj/Br/oGaz/4O7r/AAr6booA+ZP+GR/g1/0DNZ/8Hd1/hR/wyP8ABr/oGaz/AODu6/wr6booA+ZP+GR/g1/0DNZ/8Hd1/hR/wyP8Gv8AoGaz/wCDu6/wr6booA+ZP+GR/g1/0DNZ/wDB3df4Uf8ADI/wa/6Bms/+Du6/wr6booA+ZP8Ahkf4Nf8AQM1n/wAHd1/hR/wyP8Gv+gZrP/g7uv8ACvpuigD5k/4ZH+DX/QM1n/wd3X+FH/DI/wAGv+gZrP8A4O7r/CvpuigD5k/4ZH+DX/QM1n/wd3X+FH/DI/wa/wCgZrP/AIO7r/CvpuigD5k/4ZH+DX/QM1n/AMHd1/hR/wAMj/Br/oGaz/4O7r/CvpuigD5k/wCGR/g1/wBAzWf/AAd3X+FH/DI/wa/6Bms/+Du6/wAK+m6KAPmT/hkf4Nf9AzWf/B3df4Uf8Mj/AAa/6Bms/wDg7uv8K+m6KAPmT/hkf4Nf9AzWf/B3df4Uf8Mj/Br/AKBms/8Ag7uv8K+m6KAPmT/hkf4Nf9AzWf8Awd3X+FH/AAyP8Gv+gZrP/g7uv8K+m6KAPmT/AIZH+DX/AEDNZ/8AB3df4Uf8Mj/Br/oGaz/4O7r/AAr6booA+ZP+GR/g1/0DNZ/8Hd1/hR/wyP8ABr/oGaz/AODu6/wr6booA+ZP+GR/g1/0DNZ/8Hd1/hR/wyP8Gv8AoGaz/wCDu6/wr6booA+ZP+GR/g1/0DNZ/wDB3df4Uf8ADI/wa/6Bms/+Du6/wr6booA+ZP8Ahkf4Nf8AQM1n/wAHd1/hR/wyP8Gv+gZrP/g7uv8ACvpuigD5k/4ZH+DX/QM1n/wd3X+FH/DI/wAGv+gZrP8A4O7r/CvpuigD5k/4ZH+DX/QM1n/wd3X+FH/DI/wa/wCgZrP/AIO7r/CvpuigD5k/4ZH+DX/QM1n/AMHd1/hR/wAMj/Br/oGaz/4O7r/CvpuigDxfwJ8BPh78OddHiLwxa6nbal9knsi1xqk9zC9vc7DIjwyfK3zRo6k/dZFI6V7RRRQAUUUUANf7jf7rfyNfghqv/IT1D/r9uv8A0c9fve/3G/3W/ka/BDVf+QnqH/X7df8Ao56AKFFFFABX3r+w5/x/fET/AK9PDn/o7V6+Cq+9f2HP+P74if8AXp4c/wDR2r0AfoXRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBKnQ/X+gooTofr/QUUARt1P1P86Slbqfqf50lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFHVP+QbqP8A143f/pPJX4ISf6yT/fb/ANCNfvfqn/IN1H/rxu//AEnkr8EJP9ZJ/vt/6EaAGUUUUAFfoj+w7/yCfiB/1/6B/wCiNUr87q/RH9h3/kE/ED/r/wBA/wDRGqUAfd9FFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFADX+43+638jX4Iar/yE9Q/6/br/wBHPX73v9xv91v5GvwQ1X/kJ6h/1+3X/o56AKFFFFABX3r+w5/x/fET/r08Of8Ao7V6+Cq+9f2HP+P74if9enhz/wBHavQB+hdFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAEqdD9f6CihOh+v9BRQBG3U/U/zpKVup+p/nSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAUdU/wCQbqP/AF43f/pPJX4ISf6yT/fb/wBCNfvfqn/IN1H/AK8bv/0nkr8EJP8AWSf77f8AoRoAZRRRQAV9U/s5/HLwt8IbLxRbeItO12+fW7nTJrVtHt7CZY1so7xJRP8AbNQsSpY3CFNgkBAbcV4z8rUUAfp7/wANrfDL/oX/ABv/AOAGh/8Ay/o/4bW+GX/Qv+N//ADQ/wD5f1+YVFAH6e/8NrfDL/oX/G//AIAaH/8AL+j/AIbW+GX/AEL/AI3/APADQ/8A5f1+YVFAH6e/8NrfDL/oX/G//gBof/y/o/4bW+GX/Qv+N/8AwA0P/wCX9fmFRQB+nv8Aw2t8Mv8AoX/G/wD4AaH/APL+j/htb4Zf9C/43/8AADQ//l/X5hUUAfp7/wANrfDL/oX/ABv/AOAGh/8Ay/o/4bW+GX/Qv+N//ADQ/wD5f1+YVFAH6e/8NrfDL/oX/G//AIAaH/8AL+j/AIbW+GX/AEL/AI3/APADQ/8A5f1+YVFAH6e/8NrfDL/oX/G//gBof/y/o/4bW+GX/Qv+N/8AwA0P/wCX9fmFRQB+nv8Aw2t8Mv8AoX/G/wD4AaH/APL+j/htb4Zf9C/43/8AADQ//l/X5hUUAfp7/wANrfDL/oX/ABv/AOAGh/8Ay/o/4bW+GX/Qv+N//ADQ/wD5f1+YVFAH6e/8NrfDL/oX/G//AIAaH/8AL+j/AIbW+GX/AEL/AI3/APADQ/8A5f1+YVFAH6e/8NrfDL/oX/G//gBof/y/o/4bW+GX/Qv+N/8AwA0P/wCX9fmFRQB+nv8Aw2t8Mv8AoX/G/wD4AaH/APL+j/htb4Zf9C/43/8AADQ//l/X5hUUAfp7/wANrfDL/oX/ABv/AOAGh/8Ay/o/4bW+GX/Qv+N//ADQ/wD5f1+YVFAH6e/8NrfDL/oX/G//AIAaH/8AL+j/AIbW+GX/AEL/AI3/APADQ/8A5f1+YVFAH6e/8NrfDL/oX/G//gBof/y/o/4bW+GX/Qv+N/8AwA0P/wCX9fmFRQB+nv8Aw2t8Mv8AoX/G/wD4AaH/APL+j/htb4Zf9C/43/8AADQ//l/X5hUUAfp7/wANrfDL/oX/ABv/AOAGh/8Ay/o/4bW+GX/Qv+N//ADQ/wD5f1+YVFAH6e/8NrfDL/oX/G//AIAaH/8AL+j/AIbW+GX/AEL/AI3/APADQ/8A5f1+YVFAH6e/8NrfDL/oX/G//gBof/y/o/4bW+GX/Qv+N/8AwA0P/wCX9fmFRQB+nv8Aw2t8Mv8AoX/G/wD4AaH/APL+j/htb4Zf9C/43/8AADQ//l/X5hUUAfp7/wANrfDL/oX/ABv/AOAGh/8Ay/o/4bW+GX/Qv+N//ADQ/wD5f1+YVFAH6e/8NrfDL/oX/G//AIAaH/8AL+j/AIbW+GX/AEL/AI3/APADQ/8A5f1+YVFAH6e/8NrfDL/oX/G//gBof/y/o/4bW+GX/Qv+N/8AwA0P/wCX9fmFRQB+nv8Aw2t8Mv8AoX/G/wD4AaH/APL+j/htb4Zf9C/43/8AADQ//l/X5hUUAfp7/wANrfDL/oX/ABv/AOAGh/8Ay/o/4bW+GX/Qv+N//ADQ/wD5f1+YVFAH6eN+2r8MirAeH/G+SCBmx0TGSO//ABPz/KvzMvZluby6uEDBJ7iaVAwAYLJIzqGAJAIBGcEjPQmq1FABRRRQAV96/sOf8f3xE/69PDn/AKO1evgqvvX9hz/j++In/Xp4c/8AR2r0AfoXRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBKnQ/X+gooTofr/QUUARt1P1P86Slbqfqf50lABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAFHU/8AkG6h/wBeN3/6Ikr8EJP9ZJ/vt/6Ea/fiaMTQzQtyssUkbfSRCp/Q1+EXijQb7wv4i1rw9qUbR32j6ld2FwpUqGe3mdBKmesUyhZYnGVeJ0dSysCQDBooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACvvX9hz/AI/viJ/16eHP/R2r18FV+jP7Enhy9tND8Z+J54ylnrF7pemWDMpBlOkJezXkiZxui36jBEHXK+bDMmdyMFAPueiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCVOh+v9BRQnQ/X+gooAjbqfqf50lK3U/U/zpKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACvkL9o79nmX4gk+MvB8cS+LLe3WLUdOZlhTX7eBQsLRysVjj1O3jAhjaZljuYFjiaSNoY9/17RQB+COq6Nq2hX0+m6zp17pd/bOUntL62ltriJh2eOVVYA9VOMMuGUkEGs2v3k1nwx4b8RxpF4g0DRdcjj5RNW0yy1FUOc5RbuGYLzzxjnmub/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6K/cD/hU/wu/wCic+B//CV0T/5Co/4VP8Lv+ic+B/8AwldE/wDkKgD8P6UAnoCfpzX7f/8ACp/hd/0TnwP/AOEron/yFU1v8L/htaTR3Fr4A8GW88TBo5ofDOjRyxsOjI6WQZWHYqQR60AflZ8JfgN4x+KOoW0qWdxo/hdZVN94hvIHjgMKn95FpqSBTf3TAFVWLMMTYNxLEMBv1v8AC/hrSfB+gaX4a0O2Frpek2qWttHwXbGWlnmfA8y4uJmee4lIBkmkdzy1biIkaqkaLGiAKqIoVVUDAVVUAAAAAAAADgU6gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAlTofr/QUUJ0P1/oKKAI26n6n+dJSt1P1P86SgAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAJU6H6/wBBRQnQ/X+gooAjbqfqf50lK3U/U/zpKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAlTofr/QUUJ0P1/oKKAHYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAYHoPyFGB6D8hRRQAuAOgxRRRQB//2Q==';