import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:flutter/material.dart';

const termsAndConditionsUrl = 'https://snaplet.art/terms-of-service/';
const privacypolicyurl = 'https://snaplet.art/privacy-policy/';

const apiKey =
    'key-52ufVjvvgYbfEP7Q21otUGbs2J9tSc7r1SZA7MVVxv4fuTlPvWhKgfD7mX2YkfHKRbR0DwSUhuWaDDfwDXmniq6ZKioAlFfP';
//************************************************************************* */
const stableDiffusionTextToImage =
    'https://api.getimg.ai/v1/stable-diffusion/text-to-image';
const latentConsTextToImage =
    'https://api.getimg.ai/v1/latent-consistency/text-to-image';
const stableXItextToimage =
    'https://api.getimg.ai/v1/stable-diffusion-xl/text-to-image';
//************************************************************************* */
const allModels = 'https://api.getimg.ai/v1/models';
//************************************************************************* */
const stableDiffusionImageToImage =
    'https://api.getimg.ai/v1/stable-diffusion/image-to-image';
const latentConsImageToImage =
    'https://api.getimg.ai/v1/latent-consistency/image-to-image';
const stableXIimageToimage =
    'https://api.getimg.ai/v1/stable-diffusion-xl/image-to-image';
const essintialUrl = 'https://api.getimg.ai/v1/essential/text-to-image';
//************************************************************************* */
const enhansUpScale = 'https://api.getimg.ai/v1/enhancements/upscale';
const enhansFixFaces = 'https://api.getimg.ai/v1/enhancements/face-fix';
const inpaintUrl = 'https://api.getimg.ai/v1/stable-diffusion/inpaint';
const instructUrl = 'https://api.getimg.ai/v1/stable-diffusion/instruct';

List<String> images = [
  'assets/getimgimages/1.jpeg',
  'assets/getimgimages/2.png',
  'assets/getimgimages/3.jpg',
  'assets/getimgimages/4.jpg',
  'assets/getimgimages/5.jpeg',
  'assets/getimgimages/6.jpeg',
  'assets/getimgimages/7.jpeg',
  'assets/getimgimages/8.jpg',
  'assets/getimgimages/9.jpeg',
  'assets/getimgimages/10.png',
  'assets/getimgimages/11.png',
  'assets/getimgimages/12.png',
  'assets/getimgimages/13.jpeg',
  'assets/getimgimages/14.png',
  'assets/getimgimages/16.jpg',
  'assets/getimgimages/17.jpg',
  'assets/getimgimages/18.jpg',
  'assets/getimgimages/19.jpeg',
  'assets/getimgimages/20.jpeg',
  'assets/getimgimages/21.jpeg',
  'assets/getimgimages/22.jpeg',
  'assets/getimgimages/23.jpg',
  'assets/getimgimages/24.png',
  'assets/getimgimages/25.png',
  'assets/getimgimages/26.jpeg',
  'assets/getimgimages/27.png',
  'assets/getimgimages/28.jpeg',
  'assets/getimgimages/29.jpg',
  'assets/getimgimages/30.jpeg',
  'assets/getimgimages/31.jpg',
  'assets/getimgimages/33.png',
  'assets/getimgimages/34.jpeg',
  'assets/getimgimages/35.jpeg',
  'assets/getimgimages/36.jpeg',
  'assets/getimgimages/37.jpg',
  'assets/getimgimages/38.png',
  'assets/getimgimages/39.png',
  'assets/getimgimages/40.png',
  'assets/getimgimages/45.jpg',
  'assets/getimgimages/46.png',
];

List<String> inpaint = [
  'assets/getimgimages/15.jpeg',
  'assets/getimgimages/16.jpg',
  'assets/getimgimages/32.png',
  'assets/getimgimages/41.png',
];

// List<String> enhancementsimgs = [];

// List<String> instruct = [];

void showNoInternetDialog(BuildContext context) {
  showDialog(
    context: context,
    builder: (context) => AlertDialog(
      title: const Text('No Internet Connection'),
      content: const Text('Please check your internet connection and try again.'),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('OK'),
        ),
      ],
    ),
  );
}
Future<bool> checkInternetConnection() async {
  var connectivityResult = await Connectivity().checkConnectivity();
  if (connectivityResult.contains(ConnectivityResult.mobile)) {
    return true; 
  }else if(connectivityResult.contains(ConnectivityResult.wifi)){
    return true;
  }
  return false;
}


Set<String> bannedWords = {
  's3x',
  's3xy',
  's*x',
  '\$ex',
  'a\$\$',
  '@ss',
  '@n@l',
  'p*rn',
  'pr0n',
  'p0rn',
  'b00bs',
  'c0ck',
  'c*ck',
  'd1ck',
  'd!ck',
  'f*ck',
  'f@ck',
  'f*ggot',
  'f@ggot',
  'p*ssy',
  'p@ssy',
  'faggot',
  'girl hot',
  
  'gay',
  'gilf',
  'lesbian',
  'bisexual',
  'sexting',
  'strip',
  "*",
  "#",
  "2g1c",
  "blowjob",
  "g spot",
  "booty",
  "desnuda",
  "desnudo",
  "nudo",
  "nuda",
  "acrotomophilia",
  "alabama hot pocket",
  "alaskan pipeline",
  "anal",
  "anilingus",
  "anus",
  "apeshit",
  "arsehole",
  "ass",
  "asshole",
  "assmunch",
  "auto erotic",
  "autoerotic",
  "babeland",
  "baby batter",
  "baby juice",
  "ball gag",
  "ball gravy",
  "ball kicking",
  "ball licking",
  "ball sack",
  "ball sucking",
  "bangbros",
  "bangbus",
  "bareback",
  "barely legal",
  "naked",
  "barenaked",
  "bastard",
  "bastardo",
  "bastinado",
  "bbw",
  "bdsm",
  "beaner",
  "beaners",
  "beaver cleaver",
  "beaver lips",
  "beastiality",
  "bestiality",
  "big breasts",
  "big knockers",
  "big tits",
  "bimbos",
  "birdlock",
  "bitch",
  "bitches",
  "black cock",
  "blonde action",
  "blonde on blonde action",
  "blow job",
  "blow your load",
  "blue waffle",
  "blumpkin",
  "bollocks",
  "bondage",
  "boner",
  "boob",
  "boobs",
  "booty call",
  "brown showers",
  "brunette action",
  "bukkake",
  "bulldyke",
  "bullet vibe",
  "bullshit",
  "bung hole",
  "bunghole",
  "busty",
  "butt",
  "buttcheeks",
  "butthole",
  "camel toe",
  "camgirl",
  "camslut",
  "camwhore",
  "carpet muncher",
  "carpetmuncher",
  "chocolate rosebuds",
  "cialis",
  "circlejerk",
  "cleveland steamer",
  "clit",
  "clitoris",
  "clover clamps",
  "clusterfuck",
  "cock",
  "cocks",
  "coprolagnia",
  "coprophilia",
  "cornhole",
  "coon",
  "coons",
  "creampie",
  "cum",
  "cumming",
  "cumshot",
  "cumshots",
  "cunnilingus",
  "cunt",
  "darkie",
  "date rape",
  "daterape",
  "deep throat",
  "deepthroat",
  "dendrophilia",
  "dick",
  "dildo",
  "dingleberry",
  "dingleberries",
  "dirty pillows",
  "dirty sanchez",
  "doggie style",
  "doggiestyle",
  "doggy style",
  "doggystyle",
  "dog style",
  "dolcett",
  "domination",
  "dominatrix",
  "dommes",
  "donkey punch",
  "double dong",
  "double penetration",
  "dp action",
  "dry hump",
  "dvda",
  "eat my ass",
  "ecchi",
  "ejaculation",
  "erotic",
  "erotism",
  "escort",
  "eunuch",
  "fag",
  "fecal",
  'NSFW ',
  'BBC',
  'DTF',
  'HJ',
  'bj',
  'LGBTQ+',
  "felch",
  "fellatio",
  "feltch",
  "female squirting",
  "femdom",
  "figging",
  "fingerbang",
  "fingering",
  "fisting",
  "foot fetish",
  "footjob",
  "frotting",
  "fuck",
  "fuck buttons",
  "fuckin",
  "fucking",
  "fucktards",
  "fudge packer",
  "fudgepacker",
  "futanari",
  "gangbang",
  "gang bang",
  "gay sex",
  "genitals",
  "giant cock",
  "girl on",
  "girl on top",
  "girls gone wild",
  "goatcx",
  "goatse",
  "god damn",
  "gokkun",
  "golden shower",
  "goodpoop",
  "goo girl",
  "goregasm",
  "grope",
  "group sex",
  "g-spot",
  "guro",
  "hand job",
  "handjob",
  "hard core",
  "hardcore",
  "hentai",
  "homoerotic",
  "honkey",
  "hooker",
  "horny",
  "hot carl",
  "hot chick",
  "how to kill",
  "how to murder",
  "huge fat",
  "humping",
  "incest",
  "intercourse",
  "jack off",
  "jail bait",
  "jailbait",
  "jelly donut",
  "jerk off",
  "jigaboo",
  "jiggaboo",
  "jiggerboo",
  "jizz",
  "juggs",
  "kike",
  "kinbaku",
  "kinkster",
  "kinky",
  "knobbing",
  "leather restraint",
  "leather straight jacket",
  "lemon party",
  "livesex",
  "lolita",
  "lovemaking",
  "make me come",
  "male squirting",
  "masturbate",
  "masturbating",
  "masturbation",
  "menage a trois",
  "milf",
  "missionary position",
  "mong",
  "motherfucker",
  "mound of venus",
  "mr hands",
  "muff diver",
  "muffdiving",
  "nambla",
  "nawashi",
  "negro",
  "neonazi",
  "nigga",
  "nigger",
  "nig nog",
  "nimphomania",
  "nipple",
  "nipples",
  "nsfw",
  "nsfw images",
  "nude",
  "nudity",
  "nutten",
  "nympho",
  "nymphomania",
  "octopussy",
  "omorashi",
  "one guy one jar",
  "orgasm",
  "orgy",
  "paedophile",
  "paki",
  "panties",
  "panty",
  "pedobear",
  "pedophile",
  "pegging",
  "penis",
  "phone sex",
  'hot guy',
  'hot guys',
  'hot girl',
  'hot man',
  'hot woman',
  'hot women',
  'hot men',
  "piece of shit",
  "pikey",
  "pissing",
  "piss pig",
  "pisspig",
  "playboy",
  "pleasure chest",
  "pole smoker",
  "ponyplay",
  "poof",
  "poon",
  "poontang",
  "punany",
  "poop chute",
  "poopchute",
  "porn",
  "porno",
  "pornography",
  "prince albert piercing",
  "pthc",
  "pubes",
  "pussy",
  "queaf",
  "queef",
  "quim",
  "raghead",
  "raging boner",
  "rape",
  "raping",
  "rapist",
  "rectum",
  'f*cked up',
  'jerk',
  'jirk',
  "reverse cowgirl",
  "rimjob",
  "rimming",
  "rosy palm",
  "rosy palm and her 5 sisters",
  "rusty trombone",
  "sadism",
  "santorum",
  "scat",
  "schlong",
  "scissoring",
  "semen",
  "sex",
  "sexcam",
  "sexo",
  "sexy",
  "sexual",
  "sexually",
  "sexuality",
  'deck',
  "shaved beaver",
  "shaved pussy",
  "shemale",
  "shibari",
  "shit",
  "shitblimp",
  "shitty",
  "shota",
  "shrimping",
  "skeet",
  'stripping',
  "slanteye",
  "slut",
  "s&m",
  "smut",
  'nakey',
  'nake',
  'playing in ass',
  'vagina',
  "snatch",
  "snowballing",
  "sodomize",
  "sodomy",
  "spastic",
  "spic",
  "splooge",
  "splooge moose",
  "spooge",
  "spread legs",
  "spunk",
  "strap on",
  "strapon",
  "strappado",
  "strip club",
  "style doggy",
  "suck",
  "sucks",
  "suicide girls",
  "sultry women",
  "swastika",
  "swinger",
  "tainted love",
  "threesome",
  "throating",
  "thumbzilla",
  "tied up",
  "tight white",
  "tit",
  "tits",
  "titties",
  "titty",
  "tongue in a",
  "topless",
  "tosser",
  "towelhead",
  "tranny",
  "tribadism",
  "tub girl",
  "tubgirl",
  "tushy",
  "twat",
  "twink",
  "twinkie",
  "undressing",
  "upskirt",
  "urethra play",
  "urophilia",
  "venus mound",
  'sex toy',
  "viagra",
  "vibrator",
  "violet wand",
  "vorarephilia",
  "voyeur",
  "voyeurweb",
  "voyuer",
  "vulva",
  "wank",
  "wetback",
  "wet dream",
  "white power",
  "whore",
  "worldsex",
  "wrapping men",
  "wrinkled starfish",
  "xx",
  "xxx",
  "yaoi",
  "yellow showers",
  "yiffy",
  "zoophilia",
  "bychara",
  "byk",
  "chernozhopyi",
  "dolboy'eb",
  "ebalnik",
  "ebalo",
  "ebalom sch'elkat",
  "gol",
  "mudack",
  "opizdenet",
  "osto'eblo",
  "ostokhuitel'no",
  "otmudohat",
  "otpizdit",
  "otsosi",
  "padlo",
  "pedik",
  "perdet",
  "petuh",
  "pidar gnoinyj",
  "pizda",
  "pizdato",
  "pizdatyi",
  "piz'det",
  "pizdetc",
  "pizdoi nakryt'sja",
  "podi ku'evo",
  "poeben",
  "po khuy",
  "poluchit pizdy",
  "pososi moyu konfetku",
  "prissat",
  "proebat",
  "promudobl'adsksya pizdopro'ebina",
  "propezdoloch",
  "prosrat",
  "raspeezdeyi",
  "raspizdatyi",
  "shalava",
  "styervo",
  "sukin syn",
  "svodit posrat",
  "svoloch",
  "trimandoblydskiy pizdoproyob",
  "uboy",
  "vafli lovit",
  "v pizdu",
  "vyperdysh",
  "vzdrochennyi",
  "yeb vas",
  "za'ebat",
  "zaebis",
  "zalupa",
  "zalupat",
  "zasranetc",
  "zassat",
  "am",
  "amlar",
  "kaltak",
  "kaltaklar",
  "kaltaklara",
  "kaltaklarda",
  "kaltaklardan",
  "kaltakta",
  "kaltaktan",
  "orospu",
  "orospuda",
  "orospudan",
  "orospular",
  "orospulara",
  "orospularda",
  "orospulardan",
  "orospunun",
  "orospuya",
  "orospuyu",
  "otuz birci",
  "otuz bircide",
  "otuz birciden",
  "otuz birciler",
  "otuz bircilerde",
  "otuz bircilerden",
  "otuz bircilere",
  "otuz bircileri",
  "otuz bircilerin",
  "otuz bircinin",
  "otuz birciye",
  "otuz birciyi",
  "saksocu",
  "saksocuda",
  "saksocudan",
  "saksocular",
  "saksoculara",
  "saksocularda",
  "saksoculardan",
  "saksocunun",
  "saksocuya",
  "saksocuyu",
  "sik",
  "sike",
  "siker sikmez",
  "siki",
  "sikilir sikilmez",
  "sikin",
  "sikler",
  "siklerde",
  "siklerden",
  "siklere",
  "sikleri",
  "siklerin",
  "sikmek",
  "sikmemek",
  "sikte",
  "sikten",
  "siktir",
  "siktirir siktirmez",
  "yarak",
  "yaraklar",
  "yaraklara",
  "yaraklarda",
  "yaraklardan",
  "yarakta",
  "yaraktan",
  "arsle",
  "brutta",
  "discofitta",
  "fitta",
  "fittig",
  "för helvete",
  "helvete",
  "hård",
  "jävlar",
  "knulla",
  "kuk",
  "kuksås",
  "kötthuvud",
  "köttnacke",
  "moona",
  "moonade",
  "moonar",
  "moonat",
  "mutta",
  "neger",
  "olla",
  "pippa",
  "pitt",
  "prutt",
  "runka",
  "satan",
  "skita",
  "skit ner dig",
  "snedfitta",
  "snefitta",
  "stake",
  "subba",
  "sås",
  "sätta på",
  "tusan",
  "Asesinato",
  "asno",
  "Bollera",
  "Cabrón",
  "Caca",
  "Chupada",
  "Chupapollas",
  "Chupetón",
  "concha",
  "Concha de tu madre",
  "Coño",
  "Coprofagía",
  "Culo",
  "Drogas",
  "Esperma",
  "Fiesta de salchichas",
  "Follador",
  "Follar",
  "Gilipichis",
  "Gilipollas",
  "Hacer una paja",
  "Haciendo el amor",
  "Heroína",
  "Hija de puta",
  "Hijaputa",
  "Hijo de puta",
  "Hijoputa",
  "Idiota",
  "Imbécil",
  "infierno",
  "Jilipollas",
  "Kapullo",
  "Lameculos",
  "Maciza",
  "Macizorra",
  "maldito",
  "Mamada",
  "Marica",
  "Maricón",
  "Mariconazo",
  "martillo",
  "Mierda",
  "Nazi",
  "Orina",
  "Pedo",
  "Pendejo",
  "Pervertido",
  "Pezón",
  "Pinche",
  "Pis",
  "Prostituta",
  "Puta",
  "Racista",
  "Ramera",
  "Sádico",
  "Semen",
  "Sexo",
  "Sexo oral",
  "Soplagaitas",
  "Soplapollas",
  "Tetas grandes",
  "Tía buena",
  "Travesti",
  "Trio",
  "Verga",
  "vete a la mierda",
  "Vulva",
  "aborto",
  "amador",
  "ânus",
  "aranha",
  "ariano",
  "balalao",
  "bicha",
  "biscate",
  "bissexual",
  "boceta",
  "bosta",
  "braulio de borracha",
  "bumbum",
  "burro",
  "cabrao",
  "cacete",
  "cagar",
  "camisinha",
  "caralho",
  "cerveja",
  "chochota",
  "chupar",
  "cocaína",
  "coito",
  "colhoes",
  "comer",
  "cona",
  "consolo",
  "corno",
  "dar o rabo",
  "dum raio",
  "esporra",
  "filho da puta",
  "foda",
  "foda-se",
  "foder",
  "frango assado",
  "gozar",
  "grelho",
  "heroína",
  "heterosexual",
  "homem gay",
  "homoerótico",
  "homosexual",
  "inferno",
  "lésbica",
  "mama",
  "merda",
  "paneleiro",
  "passar um cheque",
  "pau",
  "peidar",
  "pênis",
  "pinto",
  "porra",
  "puta",
  "puta que pariu",
  "puta que te pariu",
  "queca",
  "sacanagem",
  "saco",
  "torneira",
  "transar",
  "vadia",
  "vai-te foder",
  "vai tomar no cu",
  "veado",
  "vibrador",
  "xana",
  "xochota",
  "burdel",
  "burdelmama",
  "chuj",
  "chujnia",
  "ciota",
  "cipa",
  "cyc",
  "debil",
  "dmuchać",
  "do kurwy nędzy",
  "dupa",
  "dupek",
  "duperele",
  "dziwka",
  "fiut",
  "gówno",
  "gówno prawda",
  "huj",
  "huj ci w dupę",
  "jajco",
  "jajko",
  "ja pierdolę",
  "jebać",
  "jebany",
  "kurwa",
  "kurwy",
  "kutafon",
  "kutas",
  "pierdolec",
  "pierdoła",
  "pojeb",
  "pojebany",
  "popierdolony",
  "robic loda",
  "robić loda",
  "ruchać",
  "rzygać",
  "skurwysyn",
  "sraczka",
  "srać",
  "suka",
  "syf",
  "zajebisty",
  "dritt",
  "drittsekk",
  "faen",
  "faen i helvete",
  "fanken",
  "fitte",
  "forbanna",
  "forbannet",
  "fy faen",
  "helvetet",
  "kukene",
  "kuker",
  "morraknuller",
  "morrapuler",
  "pakkis",
  "pikk",
  "pokker",
  "sinnsykt",
  "skitt",
  "svartheiteste",
  "abbuc",
  "qqu",
  "qqan",
  "qqant",
  "tteqqun",
  "tteqqunt",
  "aqerqur",
  "ajeḥniḍ",
  "awellaq",
  "iwellaqen",
  "iḥeččan",
  "iḥeččunen",
  "uqan",
  "taxna",
  "allupato",
  "ammucchiata",
  "anale",
  "arrapato",
  "arrusa",
  "arruso",
  "assatanato",
  "bagascia",
  "bagassa",
  "bagnarsi",
  "baldracca",
  "balle",
  "battere",
  "battona",
  "belino",
  "biga",
  "bocchinara",
  "bocchino",
  "bofilo",
  "boiata",
  "bordello",
  "brinca",
  "bucaiolo",
  "budiùlo",
  "busone",
  "cacca",
  "caciocappella",
  "cadavere",
  "cagare",
  "cagata",
  "cagna",
  "casci",
  "cazzata",
  "cazzimma",
  "cazzo",
  "cesso",
  "cazzone",
  "checca",
  "chiappa",
  "chiavare",
  "chiavata",
  "ciospo",
  "ciucciami il cazzo",
  "coglione",
  "coglioni",
  "cornuto",
  "cozza",
  "culattina",
  "culattone",
  "culo",
  "ditalino",
  "fava",
  "femminuccia",
  "fica",
  "figa",
  "figlio di buona donna",
  "figlio di puttana",
  "figone",
  "finocchio",
  "fottere",
  "fottersi",
  "fracicone",
  "fregna",
  "frocio",
  "froscio",
  "goldone",
  "guardone",
  "imbecille",
  "incazzarsi",
  "incoglionirsi",
  "ingoio",
  "leccaculo",
  "lecchino",
  "lofare",
  "loffa",
  "loffare",
  "mannaggia",
  "merdata",
  "merdoso",
  "mignotta",
  "minchia",
  "minchione",
  "mona",
  "monta",
  "montare",
  "mussa",
  "nave scuola",
  "nerchia",
  "padulo",
  "palle",
  "palloso",
  "patacca",
  "patonza",
  "pecorina",
  "pesce",
  "picio",
  "pincare",
  "pinnolone",
  "pipì",
  "pippone",
  "pirla",
  "pisciare",
  "piscio",
  "pisello",
  "pistolotto",
  "pomiciare",
  "pompa",
  "pompino",
  "porca",
  "porca madonna",
  "porca miseria",
  "porca puttana",
  "porco",
  "porco due",
  "porco zio",
  "potta",
  "puppami",
  "puttana",
  "quaglia",
  "recchione",
  "regina",
  "rincoglionire",
  "rizzarsi",
  "rompiballe",
  "rompipalle",
  "ruffiano",
  "sbattere",
  "sbattersi",
  "sborra",
  "sborrata",
  "sborrone",
  "sbrodolata",
  "scopare",
  "scopata",
  "scorreggiare",
  "sega",
  "slinguare",
  "slinguata",
  "smandrappata",
  "soccia",
  "socmel",
  "sorca",
  "spagnola",
  "spompinare",
  "sticchio",
  "stronza",
  "stronzata",
  "stronzo",
  "succhiami",
  "succhione",
  "sveltina",
  "sverginare",
  "tarzanello",
  "terrone",
  "testa di cazzo",
  "tette",
  "tirare",
  "topa",
  "troia",
  "trombare",
  "vacca",
  "vaffanculo",
  "vangare",
  "zinne",
  "zio cantante",
  "zoccola",
  "balfasz",
  "balfaszok",
  "balfaszokat",
  "balfaszt",
  "barmok",
  "barmokat",
  "barmot",
  "barom",
  "baszik",
  "bazmeg",
  "buksza",
  "bukszák",
  "bukszákat",
  "bukszát",
  "búr",
  "búrok",
  "csöcs",
  "csöcsök",
  "csöcsöket",
  "csöcsöt",
  "fasz",
  "faszfej",
  "faszfejek",
  "faszfejeket",
  "faszfejet",
  "faszok",
  "faszokat",
  "faszt",
  "fing",
  "fingok",
  "fingokat",
  "fingot",
  "franc",
  "francok",
  "francokat",
  "francot",
  "geci",
  "gecibb",
  "gecik",
  "geciket",
  "gecit",
  "kibaszott",
  "kibaszottabb",
  "kúr",
  "kurafi",
  "kurafik",
  "kurafikat",
  "kurafit",
  "kurva",
  "kurvák",
  "kurvákat",
  "kurvát",
  "leggecibb",
  "legkibaszottabb",
  "legszarabb",
  "marha",
  "marhák",
  "marhákat",
  "marhát",
  "megdöglik",
  "pele",
  "pelék",
  "picsa",
  "picsákat",
  "picsát",
  "pina",
  "pinák",
  "pinákat",
  "pinát",
  "pofa",
  "pofákat",
  "pofát",
  "pöcs",
  "pöcsök",
  "pöcsöket",
  "pöcsöt",
  "punci",
  "puncik",
  "segg",
  "seggek",
  "seggeket",
  "segget",
  "seggfej",
  "seggfejek",
  "seggfejeket",
  "seggfejet",
  "szajha",
  "szajhák",
  "szajhákat",
  "szajhát",
  "szar",
  "szarabb",
  "szarik",
  "szarok",
  "szarokat",
  "szart",
  "aand",
  "aandu",
  "balatkar",
  "balatkari",
  "behen chod",
  "beti chod",
  "bhadva",
  "bhadve",
  "bhandve",
  "bhangi",
  "bhootni ke",
  "bhosad",
  "bhosadi ke",
  "boobe",
  "chakke",
  "chinaal",
  "chinki",
  "chod",
  "chodu",
  "chodu bhagat",
  "chooche",
  "choochi",
  "choope",
  "choot",
  "choot ke baal",
  "chootia",
  "chootiya",
  "chuche",
  "chuchi",
  "chudaap",
  "chudai khanaa",
  "chudam chudai",
  "chude",
  "chut",
  "chut ka chuha",
  "chut ka churan",
  "chut ka mail",
  "chut ke baal",
  "chut ke dhakkan",
  "chut maarli",
  "chutad",
  "chutadd",
  "chutan",
  "chutia",
  "chutiya",
  "gaand",
  "gaandfat",
  "gaandmasti",
  "gaandufad",
  "gandfattu",
  "gandu",
  "gashti",
  "gasti",
  "ghassa",
  "ghasti",
  "gucchi",
  "gucchu",
  "harami",
  "haramzade",
  "hawas",
  "hawas ke pujari",
  "hijda",
  "hijra",
  "jhant",
  "jhant chaatu",
  "jhant ka keeda",
  "jhant ke baal",
  "jhant ke pissu",
  "jhantu",
  "kamine",
  "kaminey",
  "kanjar",
  "kutta",
  "kutta kamina",
  "kutte ki aulad",
  "kutte ki jat",
  "kuttiya",
  "loda",
  "lodu",
  "lund",
  "lund choos",
  "lund ka bakkal",
  "lund khajoor",
  "lundtopi",
  "lundure",
  "maa ki chut",
  "maal",
  "madar chod",
  "madarchod",
  "madhavchod",
  "mooh mein le",
  "mutth",
  "mutthal",
  "najayaz",
  "najayaz aulaad",
  "najayaz paidaish",
  "pataka",
  "patakha",
  "raand",
  "randaap",
  "randi",
  "randi rona",
  "saala",
  "saala kutta",
  "saali kutti",
  "saali randi",
  "suar",
  "suar ke lund",
  "suar ki aulad",
  "tatte",
  "tatti",
  "teri maa ka bhosada",
  "teri maa ka boba chusu",
  "teri maa ki behenchod ",
  "teri maa ki chut",
  "tharak",
  "tharki",
  "tu chuda",
  "analritter",
  "arsch",
  "arschficker",
  "arschlecker",
  "arschloch",
  "bimbo",
  "bratze",
  "bumsen",
  "bonze",
  "dödel",
  "fick",
  "ficken",
  "flittchen",
  "fotze",
  "fratze",
  "hackfresse",
  "hure",
  "hurensohn",
  "ische",
  "kackbratze",
  "kacke",
  "kacken",
  "kackwurst",
  "kampflesbe",
  "kanake",
  "kimme",
  "MILF",
  "morgenlatte",
  "mufti",
  "muschi",
  "nackt",
  "nippel",
  "nutte",
  "onanieren",
  "orgasmus",
  "pimmel",
  "pimpern",
  "pinkeln",
  "pissen",
  "pisser",
  "popel",
  "poppen",
  "reudig",
  "rosette",
  "schabracke",
  "schlampe",
  "scheiße",
  "scheisser",
  "schiesser",
  "schnackeln",
  "schwanzlutscher",
  "schwuchtel",
  "tittchen",
  "titten",
  "vögeln",
  "vollpfosten",
  "wichse",
  "wichsen",
  "wichser",
  "noune",
  "osti",
  "criss",
  "crisse",
  "calice",
  "tabarnak",
  "viarge",
  "baiser",
  "bander",
  "bigornette",
  "bite",
  "bitte",
  "bloblos",
  "bordel",
  "bourré",
  "bourrée",
  "brackmard",
  "branlage",
  "branler",
  "branlette",
  "branleur",
  "branleuse",
  "brouter le cresson",
  "caca",
  "chatte",
  "chiasse",
  "chier",
  "chiottes",
  "clito",
  "con",
  "connard",
  "connasse",
  "conne",
  "couilles",
  "cramouille",
  "cul",
  "déconne",
  "déconner",
  "emmerdant",
  "emmerder",
  "emmerdeur",
  "emmerdeuse",
  "enculé",
  "enculée",
  "enculeur",
  "enculeurs",
  "enfoiré",
  "enfoirée",
  "étron",
  "fille de pute",
  "fils de pute",
  "folle",
  "foutre",
  "gerbe",
  "gerber",
  "gouine",
  "grande folle",
  "grogniasse",
  "gueule",
  "jouir",
  "la putain de ta mère",
  "MALPT",
  "ménage à trois",
  "merde",
  "merdeuse",
  "merdeux",
  "meuf",
  "nègre",
  "nique ta mère",
  "nique ta race",
  "palucher",
  "pédale",
  "pédé",
  "péter",
  "pipi",
  "pouffiasse",
  "pousse-crotte",
  "putain",
  "pute",
  "ramoner",
  "sac à foutre",
  "sac à merde",
  "salaud",
  "salope",
  "suce",
  "tapette",
  "tanche",
  "teuch",
  "tringler",
  "trique",
  "troncher",
  "trou du cul",
  "turlute",
  "zigounette",
  "zizi",
  "alfred nussi",
  "bylsiä",
  "haahka",
  "haista paska",
  "haista vittu",
  "hatullinen",
  "helvetisti",
  "hevonkuusi",
  "hevonpaska",
  "hevonperse",
  "hevonvittu",
  "hevonvitunperse",
  "hitosti",
  "hitto",
  "huorata",
  "hässiä",
  "juosten kustu",
  "jutku",
  "jutsku",
  "jätkä",
  "kananpaska",
  "koiranpaska",
  "kuin esterin perseestä",
  "kulli",
  "kullinluikaus",
  "kuppainen",
  "kusaista",
  "kuseksia",
  "kusettaa",
  "kusi",
  "kusipää",
  "kusta",
  "kyrpiintynyt",
  "kyrpiintyä",
  "kyrpiä",
  "kyrpä",
  "kyrpänaama",
  "kyrvitys",
  "lahtari",
  "lutka",
  "molo",
  "molopää",
  "mulkero",
  "mulkku",
  "mulkvisti",
  "muna",
  "munapää",
  "munaton",
  "mutakuono",
  "mutiainen",
  "naida",
  "nainti",
  "narttu",
  "neekeri",
  "nekru",
  "nuolla persettä",
  "nussia",
  "nussija",
  "nussinta",
  "paljaalla",
  "palli",
  "pallit",
  "paneskella",
  "panettaa",
  "panna",
  "pano",
  "pantava",
  "paska",
  "paskainen",
  "paskamainen",
  "paskanmarjat",
  "paskantaa",
  "paskapuhe",
  "paskapää",
  "paskattaa",
  "paskiainen",
  "paskoa",
  "pehko",
  "pentele",
  "perkele",
  "perkeleesti",
  "persaukinen",
  "perse",
  "perseennuolija",
  "perseet olalla",
  "perspano",
  "persvako",
  "pilkunnussija",
  "pillu",
  "pillut",
  "pipari",
  "piru",
  "pyllyvako",
  "reva",
  "ripsipiirakka",
  "runkata",
  "runkkari",
  "runkkaus",
  "runkku",
  "saatanasti",
  "suklaaosasto",
  "tavara",
  "toosa",
  "tuhkaluukku",
  "tumputtaa",
  "turpasauna",
  "tussu",
  "tussukka",
  "tussut",
  "vakipano",
  "vetää käteen",
  "viiksi",
  "vittu",
  "vittuilla",
  "vittuilu",
  "vittumainen",
  "vittuuntua",
  "vittuuntunut",
  "vitun",
  "vitusti",
  "vituttaa",
  "vitutus",
  "äpärä",
  "puta ka",
  "putang ina",
  "tang ina",
  "tangina",
  "burat",
  "bayag",
  "bobo",
  "nognog",
  "tanga",
  "ulol",
  "kantot",
  "anak ka ng puta",
  "jakol",
  "bugren",
  "bugri",
  "bugru",
  "ĉiesulino",
  "ĉiesulo",
  "diofek",
  "diofeka",
  "fek",
  "feken",
  "fekfikanto",
  "feklekulo",
  "fekulo",
  "fik",
  "fikado",
  "fikema",
  "fikfek",
  "fiki",
  "fikiĝi",
  "fikiĝu",
  "fikilo",
  "fikklaŭno",
  "fikota",
  "fiku",
  "forfiki",
  "forfikiĝu",
  "forfiku",
  "forfurzu",
  "forpisi",
  "forpisu",
  "furzulo",
  "kacen",
  "kaco",
  "kacsuĉulo",
  "kojono",
  "piĉen",
  "piĉo",
  "zamenfek",
  "aardappels afgieten",
  "achter het raam zitten",
  "afberen",
  "aflebberen",
  "afrossen",
  "afrukken",
  "aftrekken",
  "afwerkplaats",
  "afzeiken",
  "afzuigen",
  "een halve man en een paardekop",
  "anita",
  "asbak",
  "aso",
  "bagger schijten",
  "balen",
  "bedonderen",
  "befborstel",
  "beffen",
  "bekken",
  "belazeren",
  "besodemieterd zijn",
  "besodemieteren",
  "beurt",
  "boemelen",
  "boerelul",
  "boerenpummel",
  "bokkelul",
  "botergeil",
  "broekhoesten",
  "brugpieper",
  "buffelen",
  "buiten de pot piesen",
  "da's kloten van de bok",
  "de ballen",
  "de hoer spelen",
  "de hond uitlaten",
  "de koffer induiken",
  "de pijp uitgaan",
  "dombo",
  "draaikont",
  "driehoog achter wonen",
  "drol",
  "drooggeiler",
  "droogkloot",
  "een beurt geven",
  "een nummertje maken",
  "een wip maken",
  "eikel",
  "engerd",
  "flamoes",
  "flikken",
  "flikker",
  "gadverdamme",
  "galbak",
  "gat",
  "gedoogzone",
  "geilneef",
  "gesodemieter",
  "godverdomme",
  "graftak",
  "gras maaien",
  "gratenkut",
  "greppeldel",
  "griet",
  "hoempert",
  "hoer",
  "hoerenbuurt",
  "hoerenloper",
  "hoerig",
  "hufter",
  "huisdealer",
  "johny",
  "kanen",
  "kettingzeug",
  "klaarkomen",
  "klerebeer",
  "klojo",
  "klooien",
  "klootjesvolk",
  "klootoog",
  "klootzak",
  "kloten",
  "knor",
  "kont",
  "kontneuken",
  "krentekakker",
  "kut",
  "kuttelikkertje",
  "kwakkie",
  "liefdesgrot",
  "lul",
  "lul-de-behanger",
  "lulhannes",
  "lummel",
  "mafketel",
  "matennaaier",
  "matje",
  "mof",
  "muts",
  "naaien",
  "naakt",
  "neuken",
  "neukstier",
  "nicht",
  "oetlul",
  "opgeilen",
  "opkankeren",
  "oprotten",
  "opsodemieteren",
  "op z'n hondjes",
  "op z'n sodemieter geven",
  "opzouten",
  "ouwehoer",
  "ouwehoeren",
  "ouwe rukker",
  "paal",
  "paardelul",
  "palen",
  "penoze",
  "piesen",
  "pijpbekkieg",
  "pijpen",
  "pik",
  "pleurislaaier",
  "poep",
  "poepen",
  "poot",
  "portiekslet",
  "pot",
  "potverdorie",
  "publiciteitsgeil",
  "raaskallen",
  "reet",
  "reetridder",
  "reet trappen, voor zijn",
  "remsporen",
  "reutelen",
  "rothoer",
  "rotzak",
  "rukhond",
  "rukken",
  "schatje",
  "schijt",
  "schijten",
  "schoft",
  "schuinsmarcheerder",
  "slempen",
  "slet",
  "sletterig",
  "slik mijn zaad",
  "snol",
  "spuiten",
  "standje",
  "standje-69",
  "stoephoer",
  "stootje",
  "stront",
  "sufferd",
  "tapijtnek",
  "teef",
  "temeier",
  "teringlijer",
  "toeter",
  "tongzoeng",
  "triootjeg",
  "trottoir prostituée",
  "trottoirteef",
  "vergallen",
  "verkloten",
  "verneuken",
  "viespeuk",
  "vingeren",
  "vleesroos",
  "voor jan lul",
  "voor jan-met-de-korte-achternaam",
  "watje",
  "welzijnsmafia",
  "wijf",
  "wippen",
  "wuftje",
  "zaadje",
  "zakkenwasser",
  "zeiken",
  "zeiker",
  "zuigen",
  "zuiplap",
  "bøsserøv",
  "fisse",
  "fissehår",
  "hestepik",
  "kussekryller",
  "lort",
  "luder",
  "pikhår",
  "pikslugeri",
  "piksutteri",
  "pis",
  "røv",
  "røvhul",
  "røvskæg",
  "røvspræke",
  "buzna",
  "čumět",
  "čurák",
  "do piče",
  "do prdele",
  "dršťka",
  "držka",
  "flundra",
  "hajzl",
  "hovno",
  "chcanky",
  "jebat",
  "kokot",
  "kokotina",
  "kunda",
  "mamrd",
  "mrdat",
  "mrdka",
  "oslošoust",
  "prcat",
  "prdel",
  "prdelka",
  "zkurvit",
  "zkurvysyn",
  "zmrd",
};
